In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Reading the violations dataset, the dataset is available publicly

In [59]:
df = pd.read_csv("violations.csv")

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16350 entries, 0 to 16349
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   case_no           16350 non-null  object
 1   ap_case_defn_key  16350 non-null  int64
 2   status_dttm       16349 non-null  object
 3   status            16350 non-null  object
 4   code              16350 non-null  object
 5   value             0 non-null      float64
 6   description       16103 non-null  object
 7   violation_stno    16350 non-null  object
 8   violation_sthigh  4124 non-null   object
 9   violation_street  16350 non-null  object
 10  violation_suffix  16211 non-null  object
 11  violation_city    16350 non-null  object
 12  violation_state   16350 non-null  object
 13  violation_zip     16348 non-null  object
 14  ward              16350 non-null  object
 15  contact_addr1     16345 non-null  object
 16  contact_addr2     2936 non-null   object
 17  contact_city      16348 non-null  object
 18  contact_state     16348 non-null  object
 19  contact_zip       16337 non-null  object
 20  sam_id            16260 non-null  float64
 21  latitude          16259 non-null  float64
 22  longitude         16259 non-null  float64
 23  location          16259 non-null  object
dtypes: float64(4), int64(1), object(19)
memory usage: 3.0+ MB

In [61]:
df.head()

,case_no,ap_case_defn_key,status_dttm,status,code,value,description,violation_stno,violation_sthigh,violation_street,...,ward,contact_addr1,contact_addr2,contact_city,contact_state,contact_zip,sam_id,latitude,longitude,location
0,V91983,1013,NaN,Closed,121.2,NaN,Unsafe and Dangerous,302,NaN,Sumner,...,01,302 Sumner St,NaN,East Boston,MA,02128,132380.0,42.367678,-71.036580,"(42.367678491254956, -71.0365803778755)"
1,V800031,1013,2024-11-19 12:09:06,Open,102.8,NaN,Maintenance,158,NaN,Neponset,...,16,158 NEPONSET AV #3,NaN,DORCHESTER,MA,02122,100778.0,42.293490,-71.050851,"(42.29348951508545, -71.05085057441715)"
2,V800021,1013,2024-11-19 11:42:13,Open,102.8,NaN,Maintenance,147,149,Draper,...,15,147 DRAPER ST,NaN,DORCHESTER,MA,02122,49414.0,42.306490,-71.065871,"(42.306489534119756, -71.06587058004278)"
3,V792005,1013,2024-11-18 14:48:16,Open,105.1,NaN,Failure to Obtain Permit,19,NaN,Bodwell,...,15,19 BODWELL ST,NaN,DORCHESTER,MA,02125,16713.0,42.312860,-71.069971,"(42.312859539299005, -71.06997057382742)"
4,V799465,1013,2024-11-15 15:39:14,Open,102.8,NaN,Maintenance,387,389,Blue Hill,...,12,619 Centre St,NaN,Boston,MA,02130,16445.0,42.311639,-71.081176,"(42.31163855469459, -71.08117560216856)"

Converting timestamp to datetime format

In [62]:
df['status_dttm']=pd.to_datetime(df['status_dttm'])

In [63]:
df['year'] = df['status_dttm'].dt.year

In [64]:
n_zip =pd.read_csv('Updated_Zip_Code_and_Neighborhood_Mapping.csv')

In [65]:
n_zip['Zip Code'] = n_zip['Zip Code'].astype(str)

In [66]:
n_zip['Zip Code'] = n_zip['Zip Code'].apply(lambda x: '0' +x)

In [67]:
df = pd.merge(df,n_zip, left_on='violation_zip', right_on='Zip Code', how='left')

In [68]:
df

,case_no,ap_case_defn_key,status_dttm,status,code,value,description,violation_stno,violation_sthigh,violation_street,...,contact_city,contact_state,contact_zip,sam_id,latitude,longitude,location,year,Zip Code,Neighbourhood
0,V91983,1013,NaT,Closed,121.2,NaN,Unsafe and Dangerous,302,NaN,Sumner,...,East Boston,MA,02128,132380.0,42.367678,-71.036580,"(42.367678491254956, -71.0365803778755)",NaN,02128,East Boston
1,V800031,1013,2024-11-19 12:09:06,Open,102.8,NaN,Maintenance,158,NaN,Neponset,...,DORCHESTER,MA,02122,100778.0,42.293490,-71.050851,"(42.29348951508545, -71.05085057441715)",2024.0,02122,Dorchester
2,V800021,1013,2024-11-19 11:42:13,Open,102.8,NaN,Maintenance,147,149,Draper,...,DORCHESTER,MA,02122,49414.0,42.306490,-71.065871,"(42.306489534119756, -71.06587058004278)",2024.0,02122,Dorchester
3,V792005,1013,2024-11-18 14:48:16,Open,105.1,NaN,Failure to Obtain Permit,19,NaN,Bodwell,...,DORCHESTER,MA,02125,16713.0,42.312860,-71.069971,"(42.312859539299005, -71.06997057382742)",2024.0,02125,Dorchester
4,V799465,1013,2024-11-15 15:39:14,Open,102.8,NaN,Maintenance,387,389,Blue Hill,...,Boston,MA,02130,16445.0,42.311639,-71.081176,"(42.31163855469459, -71.08117560216856)",2024.0,02121,Roxbury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16685,V53076,1013,2009-12-03 10:01:21,Closed,110.1,NaN,Inspections,225,NaN,Chelsea,...,EAST BOSTON,MA,02128,30417.0,42.375199,-71.032310,"(42.37519948558022, -71.03231035067552)",2009.0,02128,East Boston
16686,V53175,1013,2009-12-02 11:32:46,Closed,110.1,NaN,Inspections,2,,French,...,ROXBURY CROSSING,MA,02120,NaN,42.330640,-71.097051,"(42.330639573986325, -71.09705059581793)",2009.0,02120,Mission Hill
16687,V53175,1013,2009-12-02 11:32:46,Closed,110.1,NaN,Inspections,2,,French,...,ROXBURY CROSSING,MA,02120,NaN,42.330640,-71.097051,"(42.330639573986325, -71.09705059581793)",2009.0,02120,Roxbury
16688,V53078,1013,2009-12-01 13:39:34,Closed,110.1,NaN,Inspections,1670,NaN,Washington,...,BOSTON,MA,02118,144315.0,42.337380,-71.075271,"(42.33737954464646, -71.07527053243535)",2009.0,02118,South End
16689,V53077,1013,2009-12-01 13:18:47,Closed,5110.1,NaN,Failure to secure permit,169,NaN,Cornell,...,ROSLINDALE,MA,02131,42951.0,42.278718,-71.134020,"(42.27871763287428, -71.13401979545253)",2009.0,02131,Roslindale

Calculating number of violations every year for each unit

In [69]:
df_neigh_year = df.groupby(['Neighbourhood','year','sam_id']).size()

In [70]:
df_neigh_year = df_neigh_year.reset_index()
df_neigh_year.columns = ['Neighbourhood','Year','sam_id','Count_of_violations']

In [71]:
df_neigh_year

      Neighbourhood    Year    sam_id  Count_of_violations
0           Allston  2010.0       0.0                    1
1           Allston  2010.0    1050.0                    1
2           Allston  2010.0    1051.0                    1
3           Allston  2010.0    1737.0                    6
4           Allston  2010.0    1744.0                    1
...             ...     ...       ...                  ...
13184  West Roxbury  2024.0  140125.0                    1
13185  West Roxbury  2024.0  152903.0                    1
13186  West Roxbury  2024.0  154912.0                    1
13187  West Roxbury  2024.0  155530.0                    2
13188  West Roxbury  2024.0  350496.0                    2

[13189 rows x 4 columns]

In [72]:
len(df_neigh_year.sam_id.unique())

10123

Calculating number of bad landlords

In [73]:
df_neigh_year[df_neigh_year['Count_of_violations']>5]

      Neighbourhood    Year    sam_id  Count_of_violations
3           Allston  2010.0    1737.0                    6
127         Allston  2013.0   25142.0                    7
171         Allston  2014.0   12785.0                    6
248         Allston  2015.0   30891.0                   13
315         Allston  2017.0   53778.0                    7
...             ...     ...       ...                  ...
10979       Roxbury  2018.0   75983.0                    6
11405       Roxbury  2021.0  162187.0                    7
12552     South End  2014.0   22161.0                    6
12585     South End  2015.0   15100.0                    8
12723     South End  2018.0  371800.0                    8

[79 rows x 4 columns]

In [74]:
df_neigh_year[df_neigh_year['sam_id']==17618.0]

     Neighbourhood    Year   sam_id  Count_of_violations
4935      Downtown  2012.0  17618.0                    7
5204      Downtown  2019.0  17618.0                    2
5241      Downtown  2020.0  17618.0                    1
5333      Downtown  2022.0  17618.0                    1

In [82]:
def violations_in_prev_year(row):
    year = row['Year']
    sam = row['sam_id']
    
    prev_violations = df_neigh_year[(df_neigh_year['Year']==year-1) & (df_neigh_year['sam_id']==sam)]['Count_of_violations'].sum()
    try:
        prev_violations = df_neigh_year[(df_neigh_year['Year']==year-1) & (df_neigh_year['sam_id']==sam)]['Count_of_violations'].sum()
    except:
        prev_violations = np.nan

    return prev_violations

In [76]:
temp = df_neigh_year.copy(deep=True)

In [83]:
len(temp.apply(violations_in_prev_year,axis=1))

2010.0 0.0 0
2010.0 1050.0 0
2010.0 1051.0 0
2010.0 1737.0 0
2010.0 1744.0 0
2010.0 2649.0 0
2010.0 5120.0 0
2010.0 5132.0 0
2010.0 5910.0 0
2010.0 17253.0 0
2010.0 20065.0 0
2010.0 25086.0 0
2010.0 25090.0 0
2010.0 25119.0 0
2010.0 25149.0 0
2010.0 25183.0 0
2010.0 36983.0 0
2010.0 60619.0 0
2010.0 62614.0 0
2010.0 64567.0 0
2010.0 70974.0 0
2010.0 73270.0 0
2010.0 74821.0 0
2010.0 74834.0 0
2010.0 75176.0 0
2010.0 75177.0 0
2010.0 78027.0 0
2010.0 78029.0 0
2010.0 80894.0 0
2010.0 85983.0 0
2010.0 86414.0 0
2010.0 86431.0 0
2010.0 89029.0 0
2010.0 93560.0 0
2010.0 107720.0 0
2010.0 112517.0 0
2010.0 112519.0 0
2010.0 124116.0 0
2010.0 128400.0 0
2010.0 163737.0 0
2010.0 164222.0 0
2010.0 164938.0 0
2010.0 165429.0 0
2010.0 165554.0 0
2010.0 169339.0 0
2010.0 172706.0 0
2010.0 214022.0 0
2010.0 341051.0 0
2010.0 341543.0 0
2010.0 341942.0 0
2011.0 2650.0 0
2011.0 5133.0 0
2011.0 25101.0 0
2011.0 37683.0 0
2011.0 42367.0 0
2011.0 70974.0 1
2011.0 73263.0 0
2011.0 74821.0 1
2011.0 86411.0 0
2011.0 112504.0 0
2011.0 114208.0 0
2011.0 114815.0 0
2011.0 141273.0 0
2011.0 141287.0 0
2011.0 156442.0 0
2012.0 0.0 24
2012.0 1741.0 0
2012.0 2649.0 0
2012.0 2650.0 1
2012.0 5127.0 0
2012.0 5129.0 0
2012.0 5147.0 0
2012.0 5148.0 0
2012.0 5171.0 0
2012.0 5172.0 0
2012.0 20074.0 0
2012.0 20080.0 0
2012.0 25100.0 0
2012.0 25105.0 0
2012.0 25121.0 0
2012.0 30888.0 0
2012.0 36980.0 0
2012.0 36981.0 0
2012.0 37258.0 0
2012.0 47258.0 0
2012.0 53764.0 0
2012.0 62610.0 0
2012.0 62612.0 0
2012.0 62615.0 0
2012.0 62618.0 0
2012.0 62621.0 0
2012.0 62630.0 0
2012.0 62637.0 0
2012.0 64543.0 0
2012.0 68991.0 0
2012.0 71074.0 0
2012.0 73593.0 0
2012.0 75177.0 0
2012.0 86435.0 0
2012.0 86436.0 0
2012.0 86438.0 0
2012.0 86439.0 0
2012.0 86440.0 0
2012.0 112504.0 1
2012.0 112517.0 0
2012.0 112519.0 0
2012.0 114206.0 0
2012.0 114226.0 0
2012.0 115115.0 0
2012.0 122967.0 0
2012.0 124116.0 0
2012.0 141273.0 1
2012.0 141288.0 0
2012.0 165554.0 0
2012.0 304413.0 0
2013.0 1073.0 0
2013.0 2631.0 0
2013.0 2650.0 2
2013.0 4695.0 0
2013.0 5126.0 0
2013.0 5130.0 0
2013.0 5174.0 0
2013.0 5181.0 0
2013.0 5186.0 0
2013.0 12780.0 0
2013.0 19327.0 0
2013.0 20177.0 0
2013.0 25142.0 0
2013.0 30838.0 0
2013.0 30847.0 0
2013.0 33883.0 0
2013.0 37212.0 0
2013.0 37235.0 0
2013.0 50983.0 0
2013.0 53770.0 0
2013.0 62610.0 2
2013.0 64645.0 0
2013.0 68995.0 0
2013.0 70384.0 0
2013.0 70392.0 0
2013.0 78027.0 0
2013.0 85983.0 0
2013.0 85992.0 0
2013.0 86443.0 0
2013.0 89025.0 0
2013.0 89027.0 0
2013.0 89036.0 0
2013.0 112487.0 0
2013.0 112512.0 0
2013.0 112515.0 0
2013.0 114215.0 0
2013.0 115115.0 1
2013.0 115943.0 0
2013.0 116816.0 0
2013.0 116818.0 0
2013.0 119292.0 0
2013.0 119298.0 0
2013.0 119311.0 0
2013.0 119314.0 0
2013.0 123595.0 0
2013.0 147021.0 0
2013.0 148173.0 0
2013.0 157531.0 0
2013.0 161632.0 0
2013.0 163759.0 0
2013.0 166316.0 0
2013.0 341543.0 0
2014.0 1754.0 0
2014.0 5173.0 0
2014.0 5914.0 0
2014.0 12762.0 0
2014.0 12785.0 0
2014.0 12798.0 0
2014.0 19551.0 0
2014.0 25112.0 0
2014.0 25134.0 0
2014.0 25149.0 0
2014.0 25150.0 0
2014.0 25171.0 0
2014.0 25176.0 0
2014.0 30832.0 0
2014.0 37126.0 0
2014.0 51011.0 0
2014.0 53770.0 1
2014.0 53772.0 0
2014.0 56626.0 0
2014.0 56631.0 0
2014.0 60622.0 0
2014.0 62616.0 0
2014.0 64645.0 2
2014.0 70964.0 0
2014.0 70968.0 0
2014.0 70994.0 0
2014.0 73268.0 0
2014.0 73589.0 0
2014.0 73593.0 0
2014.0 73595.0 0
2014.0 80890.0 0
2014.0 85987.0 0
2014.0 86411.0 0
2014.0 86423.0 0
2014.0 86428.0 0
2014.0 86429.0 0
2014.0 86431.0 0
2014.0 86436.0 0
2014.0 86444.0 0
2014.0 86446.0 0
2014.0 109170.0 0
2014.0 112521.0 0
2014.0 112525.0 0
2014.0 114164.0 0
2014.0 114226.0 0
2014.0 115115.0 1
2014.0 115943.0 4
2014.0 116817.0 0
2014.0 119388.0 0
2014.0 141281.0 0
2014.0 148170.0 0
2014.0 148173.0 1
2014.0 154638.0 0
2014.0 161849.0 0
2014.0 165210.0 0
2014.0 166108.0 0
2014.0 166220.0 0
2014.0 166316.0 1
2014.0 168619.0 0
2014.0 169042.0 0
2014.0 201011.0 0
2014.0 214025.0 0
2014.0 253252.0 0
2014.0 306897.0 0
2014.0 347242.0 0
2014.0 352109.0 0
2015.0 1767.0 0
2015.0 4690.0 0
2015.0 5147.0 0
2015.0 5148.0 0
2015.0 5171.0 0
2015.0 5190.0 0
2015.0 5906.0 0
2015.0 12798.0 2
2015.0 20078.0 0
2015.0 20177.0 0
2015.0 25303.0 0
2015.0 30834.0 0
2015.0 30836.0 0
2015.0 30838.0 0
2015.0 30888.0 0
2015.0 30891.0 0
2015.0 37121.0 0
2015.0 53771.0 0
2015.0 54993.0 0
2015.0 60622.0 1
2015.0 64567.0 0
2015.0 69009.0 0
2015.0 70973.0 0
2015.0 71074.0 0
2015.0 71084.0 0
2015.0 74768.0 0
2015.0 74821.0 0
2015.0 75228.0 0
2015.0 75230.0 0
2015.0 86412.0 0
2015.0 86414.0 0
2015.0 86428.0 1
2015.0 86432.0 0
2015.0 112486.0 0
2015.0 112493.0 0
2015.0 112511.0 0
2015.0 112524.0 0
2015.0 112526.0 0
2015.0 119300.0 0
2015.0 122969.0 0
2015.0 122979.0 0
2015.0 148232.0 0
2015.0 156467.0 0
2015.0 162569.0 0
2015.0 163755.0 0
2015.0 165124.0 0
2015.0 166105.0 0
2015.0 168619.0 1
2015.0 201228.0 0
2015.0 353118.0 0
2015.0 355204.0 0
2015.0 355205.0 0
2015.0 355206.0 0
2016.0 1737.0 0
2016.0 15834.0 0
2016.0 25164.0 0
2016.0 53778.0 0
2016.0 60607.0 0
2016.0 60608.0 0
2016.0 64645.0 0
2016.0 70337.0 0
2016.0 70350.0 0
2016.0 71081.0 0
2016.0 71084.0 1
2016.0 74821.0 2
2016.0 74826.0 0
2016.0 99633.0 0
2016.0 114831.0 0
2016.0 114832.0 0
2016.0 115104.0 0
2016.0 124117.0 0
2016.0 169042.0 0
2016.0 350465.0 0
2016.0 404741.0 0
2017.0 3810.0 0
2017.0 5137.0 0
2017.0 5173.0 0
2017.0 12553.0 0
2017.0 20073.0 0
2017.0 20075.0 0
2017.0 25136.0 0
2017.0 37276.0 0
2017.0 53778.0 1
2017.0 54988.0 0
2017.0 60645.0 0
2017.0 62611.0 0
2017.0 62617.0 0
2017.0 68991.0 0
2017.0 74821.0 3
2017.0 99631.0 0
2017.0 99632.0 0
2017.0 99633.0 1
2017.0 115095.0 0
2017.0 115115.0 0
2017.0 119300.0 0
2017.0 119446.0 0
2017.0 341863.0 0
2017.0 422733.0 0
2018.0 20081.0 0
2018.0 20169.0 0
2018.0 25176.0 0
2018.0 51011.0 0
2018.0 70397.0 0
2018.0 107668.0 0
2018.0 114262.0 0
2018.0 115115.0 1
2018.0 119314.0 0
2018.0 119447.0 0
2018.0 148226.0 0
2018.0 341911.0 0
2018.0 341912.0 0
2019.0 5124.0 0
2019.0 37258.0 0
2019.0 37352.0 0
2019.0 62619.0 0
2019.0 67215.0 0
2019.0 70964.0 0
2019.0 87080.0 0
2019.0 155896.0 0
2019.0 163740.0 0
2019.0 163759.0 0
2019.0 171735.0 0
2019.0 438994.0 0
2020.0 0.0 3
2020.0 37026.0 0
2020.0 37311.0 0
2020.0 37443.0 0
2020.0 70394.0 0
2020.0 85983.0 0
2020.0 122991.0 0
2021.0 5905.0 0
2021.0 25105.0 0
2021.0 37065.0 0
2021.0 62608.0 0
2021.0 65420.0 0
2021.0 73531.0 0
2021.0 78034.0 0
2021.0 85983.0 1
2021.0 89032.0 0
2021.0 119447.0 0
2021.0 122980.0 0
2021.0 405049.0 0
2022.0 5114.0 0
2022.0 5130.0 0
2022.0 5131.0 0
2022.0 18746.0 0
2022.0 20107.0 0
2022.0 20108.0 0
2022.0 25093.0 0
2022.0 25132.0 0
2022.0 54981.0 0
2022.0 62604.0 0
2022.0 62618.0 0
2022.0 67237.0 0
2022.0 67238.0 0
2022.0 70956.0 0
2022.0 74831.0 0
2022.0 86421.0 0
2022.0 89191.0 0
2022.0 112516.0 0
2022.0 112519.0 0
2022.0 112522.0 0
2022.0 162571.0 0
2022.0 166220.0 0
2022.0 171738.0 0
2023.0 2631.0 0
2023.0 5173.0 0
2023.0 25083.0 0
2023.0 25126.0 0
2023.0 59257.0 0
2023.0 74831.0 1
2023.0 78030.0 0
2023.0 86421.0 1
2023.0 107588.0 0
2023.0 112504.0 0
2023.0 112514.0 0
2023.0 112519.0 1
2023.0 119328.0 0
2023.0 127489.0 0
2023.0 141274.0 0
2024.0 1737.0 0
2024.0 1767.0 0
2024.0 1795.0 0
2024.0 4690.0 0
2024.0 5147.0 0
2024.0 5182.0 0
2024.0 20075.0 0
2024.0 25134.0 0
2024.0 25171.0 0
2024.0 30888.0 0
2024.0 36980.0 0
2024.0 42367.0 0
2024.0 60645.0 0
2024.0 62619.0 0
2024.0 64567.0 0
2024.0 75177.0 0
2024.0 85983.0 0
2024.0 86412.0 0
2024.0 86431.0 0
2024.0 107682.0 0
2024.0 112486.0 0
2024.0 112511.0 0
2024.0 112513.0 0
2024.0 112515.0 0
2024.0 112519.0 1
2024.0 115104.0 0
2024.0 124116.0 0
2024.0 141285.0 0
2024.0 161850.0 0
2024.0 165429.0 0
2024.0 169042.0 0
2024.0 439319.0 0
2010.0 0.0 0
2010.0 3815.0 0
2010.0 4012.0 0
2010.0 4014.0 0
2010.0 9979.0 0
2010.0 18372.0 0
2010.0 33228.0 0
2010.0 35631.0 0
2010.0 35688.0 0
2010.0 38510.0 0
2010.0 76237.0 0
2010.0 90286.0 0
2010.0 90931.0 0
2010.0 96708.0 0
2010.0 101337.0 0
2010.0 101383.0 0
2010.0 101992.0 0
2010.0 102445.0 0
2010.0 131663.0 0
2010.0 131668.0 0
2010.0 155945.0 0
2010.0 161083.0 0
2010.0 163597.0 0
2011.0 18322.0 0
2011.0 18323.0 0
2011.0 32640.0 0
2011.0 32642.0 0
2011.0 39677.0 0
2011.0 39831.0 0
2011.0 46439.0 0
2011.0 90598.0 0
2011.0 90656.0 0
2011.0 90954.0 0
2011.0 101337.0 1
2011.0 101637.0 0
2011.0 101994.0 0
2011.0 143061.0 0
2012.0 4012.0 0
2012.0 15034.0 0
2012.0 18312.0 0
2012.0 18313.0 0
2012.0 18361.0 0
2012.0 18396.0 0
2012.0 18397.0 0
2012.0 28667.0 0
2012.0 28717.0 0
2012.0 35476.0 0
2012.0 41149.0 0
2012.0 41241.0 0
2012.0 55323.0 0
2012.0 90319.0 0
2012.0 90569.0 0
2012.0 90893.0 0
2012.0 101349.0 0
2012.0 101470.0 0
2012.0 101577.0 0
2012.0 110173.0 0
2012.0 137458.0 0
2012.0 137459.0 0
2012.0 137460.0 0
2012.0 137461.0 0
2012.0 137467.0 0
2012.0 155737.0 0
2012.0 157315.0 0
2012.0 157607.0 0
2012.0 162438.0 0
2012.0 163193.0 0
2013.0 3921.0 0
2013.0 9479.0 0
2013.0 9480.0 0
2013.0 10019.0 0
2013.0 10686.0 0
2013.0 10900.0 0
2013.0 11166.0 0
2013.0 11232.0 0
2013.0 11342.0 0
2013.0 18101.0 0
2013.0 18370.0 0
2013.0 18371.0 0
2013.0 18373.0 0
2013.0 18374.0 0
2013.0 18380.0 0
2013.0 18385.0 0
2013.0 18393.0 0
2013.0 18640.0 0
2013.0 37755.0 0
2013.0 38463.0 0
2013.0 39667.0 0
2013.0 41198.0 0
2013.0 41241.0 1
2013.0 90893.0 1
2013.0 90963.0 0
2013.0 101450.0 0
2013.0 101461.0 0
2013.0 101470.0 1
2013.0 101472.0 0
2013.0 101635.0 0
2013.0 121155.0 0
2013.0 131643.0 0
2013.0 137464.0 0
2013.0 142931.0 0
2013.0 340981.0 0
2013.0 341212.0 0
2013.0 347387.0 0
2014.0 0.0 14
2014.0 3842.0 0
2014.0 3910.0 0
2014.0 9480.0 1
2014.0 9488.0 0
2014.0 9712.0 0
2014.0 9802.0 0
2014.0 10896.0 0
2014.0 10897.0 0
2014.0 10899.0 0
2014.0 18101.0 1
2014.0 18351.0 0
2014.0 18397.0 0
2014.0 28615.0 0
2014.0 28658.0 0
2014.0 32655.0 0
2014.0 39680.0 0
2014.0 46257.0 0
2014.0 55592.0 0
2014.0 90548.0 0
2014.0 91231.0 0
2014.0 93978.0 0
2014.0 101317.0 0
2014.0 101439.0 0
2014.0 101483.0 0
2014.0 101577.0 0
2014.0 120987.0 0
2014.0 137783.0 0
2014.0 137791.0 0
2014.0 142929.0 0
2014.0 157041.0 0
2014.0 157161.0 0
2014.0 157244.0 0
2014.0 157452.0 0
2014.0 163131.0 0
2014.0 163590.0 0
2014.0 164168.0 0
2015.0 3856.0 0
2015.0 3910.0 1
2015.0 4810.0 0
2015.0 9488.0 1
2015.0 9501.0 0
2015.0 9550.0 0
2015.0 9578.0 0
2015.0 9602.0 0
2015.0 9635.0 0
2015.0 9641.0 0
2015.0 10033.0 0
2015.0 10305.0 0
2015.0 11059.0 0
2015.0 18318.0 0
2015.0 18322.0 0
2015.0 18638.0 0
2015.0 25712.0 0
2015.0 25757.0 0
2015.0 28623.0 0
2015.0 33209.0 0
2015.0 37110.0 0
2015.0 38690.0 0
2015.0 39262.0 0
2015.0 39900.0 0
2015.0 40064.0 0
2015.0 40272.0 0
2015.0 40815.0 0
2015.0 41226.0 0
2015.0 46504.0 0
2015.0 55624.0 0
2015.0 64929.0 0
2015.0 90310.0 0
2015.0 90319.0 0
2015.0 90334.0 0
2015.0 90336.0 0
2015.0 90343.0 0
2015.0 90524.0 0
2015.0 101315.0 0
2015.0 101346.0 0
2015.0 101367.0 0
2015.0 101372.0 0
2015.0 101430.0 0
2015.0 101434.0 0
2015.0 101436.0 0
2015.0 101438.0 0
2015.0 101440.0 0
2015.0 101446.0 0
2015.0 101466.0 0
2015.0 101475.0 0
2015.0 101477.0 0
2015.0 101577.0 1
2015.0 101992.0 0
2015.0 131637.0 0
2015.0 131638.0 0
2015.0 137477.0 0
2015.0 142980.0 0
2015.0 153234.0 0
2015.0 157041.0 2
2015.0 162423.0 0
2015.0 165216.0 0
2015.0 167428.0 0
2015.0 167591.0 0
2015.0 168039.0 0
2015.0 168052.0 0
2015.0 341128.0 0
2015.0 353806.0 0
2016.0 4817.0 0
2016.0 4827.0 0
2016.0 9535.0 0
2016.0 10050.0 0
2016.0 10069.0 0
2016.0 10260.0 0
2016.0 10285.0 0
2016.0 10626.0 0
2016.0 18415.0 0
2016.0 26648.0 0
2016.0 28667.0 0
2016.0 28681.0 0
2016.0 33282.0 0
2016.0 35660.0 0
2016.0 35663.0 0
2016.0 40064.0 1
2016.0 40272.0 1
2016.0 41226.0 1
2016.0 46334.0 0
2016.0 46421.0 0
2016.0 55624.0 1
2016.0 56953.0 0
2016.0 62827.0 0
2016.0 76238.0 0
2016.0 84616.0 0
2016.0 90310.0 1
2016.0 90319.0 1
2016.0 90324.0 0
2016.0 90334.0 2
2016.0 90336.0 2
2016.0 90343.0 1
2016.0 90372.0 0
2016.0 90446.0 0
2016.0 91493.0 0
2016.0 91601.0 0
2016.0 93929.0 0
2016.0 101436.0 1
2016.0 101437.0 0
2016.0 101438.0 1
2016.0 101440.0 1
2016.0 101472.0 0
2016.0 121155.0 0
2016.0 150574.0 0
2016.0 157607.0 0
2016.0 162457.0 0
2016.0 163448.0 0
2016.0 163602.0 0
2016.0 167424.0 0
2016.0 167590.0 0
2016.0 168054.0 0
2016.0 171012.0 0
2016.0 172953.0 0
2016.0 340858.0 0
2016.0 350829.0 0
2017.0 0.0 3
2017.0 4091.0 0
2017.0 9550.0 0
2017.0 9758.0 0
2017.0 9813.0 0
2017.0 9819.0 0
2017.0 10069.0 1
2017.0 10721.0 0
2017.0 18321.0 0
2017.0 18333.0 0
2017.0 33226.0 0
2017.0 33288.0 0
2017.0 38674.0 0
2017.0 45830.0 0
2017.0 46509.0 0
2017.0 56953.0 1
2017.0 64929.0 0
2017.0 66066.0 0
2017.0 76238.0 2
2017.0 84661.0 0
2017.0 90324.0 1
2017.0 90533.0 0
2017.0 90848.0 0
2017.0 90850.0 0
2017.0 90851.0 0
2017.0 94003.0 0
2017.0 101330.0 0
2017.0 101535.0 0
2017.0 102512.0 0
2017.0 161890.0 0
2017.0 162417.0 0
2017.0 168743.0 0
2018.0 0.0 4
2018.0 4111.0 0
2018.0 9477.0 0
2018.0 9511.0 0
2018.0 9758.0 1
2018.0 9819.0 1
2018.0 10614.0 0
2018.0 10721.0 1
2018.0 11080.0 0
2018.0 11246.0 0
2018.0 18322.0 0
2018.0 18415.0 0
2018.0 25581.0 0
2018.0 25688.0 0
2018.0 28740.0 0
2018.0 84608.0 0
2018.0 87852.0 0
2018.0 90343.0 0
2018.0 90405.0 0
2018.0 90486.0 0
2018.0 101453.0 0
2018.0 101997.0 0
2018.0 120942.0 0
2018.0 120974.0 0
2018.0 120988.0 0
2018.0 131648.0 0
2018.0 137458.0 0
2018.0 156038.0 0
2018.0 161890.0 1
2018.0 162438.0 0
2018.0 163712.0 0
2019.0 0.0 1
2019.0 605.0 0
2019.0 4001.0 0
2019.0 9819.0 1
2019.0 10338.0 0
2019.0 10530.0 0
2019.0 10721.0 1
2019.0 11247.0 0
2019.0 15007.0 0
2019.0 28821.0 0
2019.0 35631.0 0
2019.0 39900.0 0
2019.0 41283.0 0
2019.0 43213.0 0
2019.0 45830.0 0
2019.0 46522.0 0
2019.0 55602.0 0
2019.0 56953.0 0
2019.0 56958.0 0
2019.0 66042.0 0
2019.0 84594.0 0
2019.0 90310.0 0
2019.0 90575.0 0
2019.0 90636.0 0
2019.0 90706.0 0
2019.0 90824.0 0
2019.0 90856.0 0
2019.0 90860.0 0
2019.0 101375.0 0
2019.0 101471.0 0
2019.0 101985.0 0
2019.0 101998.0 0
2019.0 120902.0 0
2019.0 120988.0 1
2019.0 120992.0 0
2019.0 131637.0 0
2019.0 137486.0 0
2019.0 143075.0 0
2019.0 150583.0 0
2019.0 157041.0 0
2019.0 161890.0 1
2019.0 161897.0 0
2019.0 162452.0 0
2019.0 163712.0 1
2019.0 170055.0 0
2019.0 345773.0 0
2020.0 0.0 3
2020.0 4091.0 0
2020.0 4847.0 0
2020.0 10606.0 0
2020.0 10679.0 0
2020.0 10686.0 0
2020.0 10721.0 1
2020.0 10910.0 0
2020.0 18333.0 0
2020.0 18340.0 0
2020.0 25611.0 0
2020.0 28652.0 0
2020.0 39826.0 0
2020.0 39972.0 0
2020.0 41283.0 2
2020.0 57014.0 0
2020.0 79006.0 0
2020.0 84594.0 1
2020.0 90824.0 1
2020.0 93983.0 0
2020.0 101330.0 0
2020.0 101338.0 0
2020.0 101455.0 0
2020.0 101471.0 1
2020.0 101997.0 0
2020.0 120974.0 0
2020.0 120988.0 1
2020.0 157244.0 0
2020.0 161583.0 0
2020.0 161890.0 1
2020.0 163125.0 0
2020.0 163712.0 2
2021.0 0.0 2
2021.0 9519.0 0
2021.0 9667.0 0
2021.0 25764.0 0
2021.0 35551.0 0
2021.0 41283.0 1
2021.0 64880.0 0
2021.0 90310.0 0
2021.0 101439.0 0
2021.0 101491.0 0
2021.0 131637.0 0
2021.0 158173.0 0
2021.0 345598.0 0
2022.0 3815.0 0
2022.0 3829.0 0
2022.0 3862.0 0
2022.0 3864.0 0
2022.0 3865.0 0
2022.0 3871.0 0
2022.0 4007.0 0
2022.0 4033.0 0
2022.0 4131.0 0
2022.0 4136.0 0
2022.0 4145.0 0
2022.0 4151.0 0
2022.0 10337.0 0
2022.0 18328.0 0
2022.0 18389.0 0
2022.0 39860.0 0
2022.0 39873.0 0
2022.0 46340.0 0
2022.0 46523.0 0
2022.0 56963.0 0
2022.0 64929.0 0
2022.0 66074.0 0
2022.0 84589.0 0
2022.0 90310.0 1
2022.0 90319.0 0
2022.0 91601.0 0
2022.0 101984.0 0
2022.0 137469.0 0
2022.0 137617.0 0
2022.0 142944.0 0
2022.0 158150.0 0
2022.0 163461.0 0
2022.0 167427.0 0
2022.0 167428.0 0
2022.0 343513.0 0
2022.0 344768.0 0
2023.0 10033.0 0
2023.0 10721.0 0
2023.0 11259.0 0
2023.0 11351.0 0
2023.0 18313.0 0
2023.0 18381.0 0
2023.0 18415.0 0
2023.0 28641.0 0
2023.0 32625.0 0
2023.0 37778.0 0
2023.0 38560.0 0
2023.0 39678.0 0
2023.0 41283.0 0
2023.0 55340.0 0
2023.0 55565.0 0
2023.0 90567.0 0
2023.0 90899.0 0
2023.0 90931.0 0
2023.0 101330.0 0
2023.0 101345.0 0
2023.0 101995.0 0
2023.0 101996.0 0
2023.0 150583.0 0
2023.0 153241.0 0
2023.0 340858.0 0
2024.0 0.0 1
2024.0 3862.0 0
2024.0 3864.0 0
2024.0 4080.0 0
2024.0 4131.0 0
2024.0 4151.0 0
2024.0 9501.0 0
2024.0 9550.0 0
2024.0 10033.0 1
2024.0 10743.0 0
2024.0 18313.0 1
2024.0 18381.0 2
2024.0 33146.0 0
2024.0 33282.0 0
2024.0 39738.0 0
2024.0 39825.0 0
2024.0 55343.0 0
2024.0 90302.0 0
2024.0 90310.0 0
2024.0 90319.0 0
2024.0 90405.0 0
2024.0 93942.0 0
2024.0 101334.0 0
2024.0 120987.0 0
2024.0 158131.0 0
2024.0 171613.0 0
2024.0 341077.0 0
2024.0 367825.0 0
2009.0 11072.0 0
2010.0 0.0 0
2010.0 11991.0 0
2010.0 12991.0 0
2010.0 13000.0 0
2010.0 19556.0 0
2010.0 26893.0 0
2010.0 26902.0 0
2010.0 29137.0 0
2010.0 29172.0 0
2010.0 31381.0 0
2010.0 80175.0 0
2010.0 98503.0 0
2010.0 138003.0 0
2010.0 155704.0 0
2010.0 163153.0 0
2011.0 0.0 45
2011.0 9701.0 0
2011.0 26902.0 1
2011.0 29137.0 2
2011.0 29152.0 0
2011.0 110774.0 0
2011.0 123774.0 0
2011.0 123776.0 0
2011.0 123777.0 0
2011.0 144935.0 0
2011.0 161874.0 0
2011.0 163153.0 3
2011.0 169531.0 0
2011.0 340652.0 0
2011.0 343210.0 0
2012.0 10053.0 0
2012.0 15792.0 0
2012.0 31437.0 0
2012.0 98611.0 0
2012.0 170408.0 0
2013.0 0.0 36
2013.0 9666.0 0
2013.0 11517.0 0
2013.0 11909.0 0
2013.0 20243.0 0
2013.0 26926.0 0
2013.0 31327.0 0
2013.0 31511.0 0
2013.0 98768.0 0
2013.0 110762.0 0
2013.0 110772.0 0
2013.0 123777.0 0
2013.0 136811.0 0
2013.0 142038.0 0
2013.0 144935.0 0
2013.0 162104.0 0
2013.0 169533.0 0
2013.0 171030.0 0
2014.0 11478.0 0
2014.0 29137.0 0
2014.0 31327.0 2
2014.0 31390.0 0
2014.0 98583.0 0
2014.0 98612.0 0
2014.0 170408.0 0
2014.0 351708.0 0
2015.0 11478.0 1
2015.0 12370.0 0
2015.0 12466.0 0
2015.0 12467.0 0
2015.0 29137.0 1
2015.0 29162.0 0
2015.0 29163.0 0
2015.0 31404.0 0
2015.0 31438.0 0
2015.0 80103.0 0
2015.0 98502.0 0
2015.0 98542.0 0
2015.0 98544.0 0
2015.0 98545.0 0
2015.0 98742.0 0
2015.0 106089.0 0
2015.0 139291.0 0
2015.0 144637.0 0
2015.0 163308.0 0
2015.0 167912.0 0
2015.0 169108.0 0
2016.0 11266.0 0
2016.0 21785.0 0
2016.0 29159.0 0
2016.0 31437.0 0
2016.0 98542.0 1
2016.0 98544.0 1
2016.0 98545.0 1
2016.0 98717.0 0
2016.0 98745.0 0
2016.0 150875.0 0
2016.0 171880.0 0
2016.0 278969.0 0
2016.0 343210.0 0
2016.0 347140.0 0
2017.0 12214.0 0
2017.0 43808.0 0
2017.0 98532.0 0
2017.0 98545.0 2
2017.0 103543.0 0
2017.0 110627.0 0
2017.0 139287.0 0
2017.0 144637.0 0
2017.0 168952.0 0
2018.0 12021.0 0
2018.0 12214.0 1
2018.0 12219.0 0
2018.0 12226.0 0
2018.0 13000.0 0
2018.0 31521.0 0
2018.0 98542.0 0
2018.0 98725.0 0
2018.0 110711.0 0
2018.0 116213.0 0
2018.0 123779.0 0
2018.0 162368.0 0
2019.0 11866.0 0
2019.0 13000.0 2
2019.0 15792.0 0
2019.0 17550.0 0
2019.0 26907.0 0
2019.0 31471.0 0
2019.0 98542.0 1
2019.0 98544.0 0
2019.0 98545.0 0
2019.0 106095.0 0
2019.0 110676.0 0
2019.0 110705.0 0
2019.0 110707.0 0
2019.0 110788.0 0
2019.0 163308.0 0
2020.0 15794.0 0
2020.0 20225.0 0
2020.0 31328.0 0
2020.0 31437.0 0
2020.0 31471.0 1
2020.0 98544.0 1
2020.0 98727.0 0
2020.0 110676.0 1
2020.0 123777.0 0
2020.0 130062.0 0
2020.0 136811.0 0
2020.0 163308.0 1
2021.0 15792.0 0
2021.0 29159.0 0
2021.0 31471.0 1
2021.0 123777.0 1
2021.0 139287.0 0
2021.0 139291.0 0
2021.0 163961.0 0
2022.0 10053.0 0
2022.0 15794.0 0
2022.0 29152.0 0
2022.0 31381.0 0
2022.0 43806.0 0
2022.0 98727.0 0
2022.0 98779.0 0
2022.0 98802.0 0
2022.0 156399.0 0
2022.0 163942.0 0
2022.0 169531.0 0
2022.0 356415.0 0
2022.0 356512.0 0
2023.0 11236.0 0
2023.0 11266.0 0
2023.0 12466.0 0
2023.0 26940.0 0
2023.0 31437.0 0
2023.0 69055.0 0
2023.0 150206.0 0
2024.0 12236.0 0
2024.0 12466.0 1
2024.0 15794.0 0
2024.0 29152.0 0
2024.0 116213.0 0
2024.0 138003.0 0
2024.0 144935.0 0
2024.0 144937.0 0
2024.0 150206.0 1
2024.0 157146.0 0
2024.0 356415.0 0
2009.0 150792.0 0
2010.0 0.0 0
2010.0 12557.0 0
2010.0 12756.0 0
2010.0 12768.0 0
2010.0 15449.0 0
2010.0 31864.0 0
2010.0 32318.0 0
2010.0 33665.0 0
2010.0 37764.0 0
2010.0 38426.0 0
2010.0 38777.0 0
2010.0 44254.0 0
2010.0 47782.0 0
2010.0 48048.0 0
2010.0 48060.0 0
2010.0 50300.0 0
2010.0 50306.0 0
2010.0 51469.0 0
2010.0 54086.0 0
2010.0 54092.0 0
2010.0 59598.0 0
2010.0 63508.0 0
2010.0 81625.0 0
2010.0 83014.0 0
2010.0 83029.0 0
2010.0 83356.0 0
2010.0 84049.0 0
2010.0 84743.0 0
2010.0 85997.0 0
2010.0 89446.0 0

13189

In [84]:
temp['prev_year_violation'] = temp.apply(violations_in_prev_year,axis=1)

2010.0 0.0 0
2010.0 1050.0 0
2010.0 1051.0 0
2010.0 1737.0 0
2010.0 1744.0 0
2010.0 2649.0 0
2010.0 5120.0 0
2010.0 5132.0 0
2010.0 5910.0 0
2010.0 17253.0 0
2010.0 20065.0 0
2010.0 25086.0 0
2010.0 25090.0 0
2010.0 25119.0 0
2010.0 25149.0 0
2010.0 25183.0 0
2010.0 36983.0 0
2010.0 60619.0 0
2010.0 62614.0 0
2010.0 64567.0 0
2010.0 70974.0 0
2010.0 73270.0 0
2010.0 74821.0 0
2010.0 74834.0 0
2010.0 75176.0 0
2010.0 75177.0 0
2010.0 78027.0 0
2010.0 78029.0 0
2010.0 80894.0 0
2010.0 85983.0 0
2010.0 86414.0 0
2010.0 86431.0 0
2010.0 89029.0 0
2010.0 93560.0 0
2010.0 107720.0 0
2010.0 112517.0 0
2010.0 112519.0 0
2010.0 124116.0 0
2010.0 128400.0 0
2010.0 163737.0 0
2010.0 164222.0 0
2010.0 164938.0 0
2010.0 165429.0 0
2010.0 165554.0 0
2010.0 169339.0 0
2010.0 172706.0 0
2010.0 214022.0 0
2010.0 341051.0 0
2010.0 341543.0 0
2010.0 341942.0 0
2011.0 2650.0 0
2011.0 5133.0 0
2011.0 25101.0 0
2011.0 37683.0 0
2011.0 42367.0 0
2011.0 70974.0 1
2011.0 73263.0 0
2011.0 74821.0 1
2011.0 86411.0 0
2011.0 112504.0 0
2011.0 114208.0 0
2011.0 114815.0 0
2011.0 141273.0 0
2011.0 141287.0 0
2011.0 156442.0 0
2012.0 0.0 24
2012.0 1741.0 0
2012.0 2649.0 0
2012.0 2650.0 1
2012.0 5127.0 0
2012.0 5129.0 0
2012.0 5147.0 0
2012.0 5148.0 0
2012.0 5171.0 0
2012.0 5172.0 0
2012.0 20074.0 0
2012.0 20080.0 0
2012.0 25100.0 0
2012.0 25105.0 0
2012.0 25121.0 0
2012.0 30888.0 0
2012.0 36980.0 0
2012.0 36981.0 0
2012.0 37258.0 0
2012.0 47258.0 0
2012.0 53764.0 0
2012.0 62610.0 0
2012.0 62612.0 0
2012.0 62615.0 0
2012.0 62618.0 0
2012.0 62621.0 0
2012.0 62630.0 0
2012.0 62637.0 0
2012.0 64543.0 0
2012.0 68991.0 0
2012.0 71074.0 0
2012.0 73593.0 0
2012.0 75177.0 0
2012.0 86435.0 0
2012.0 86436.0 0
2012.0 86438.0 0
2012.0 86439.0 0
2012.0 86440.0 0
2012.0 112504.0 1
2012.0 112517.0 0
2012.0 112519.0 0
2012.0 114206.0 0
2012.0 114226.0 0
2012.0 115115.0 0
2012.0 122967.0 0
2012.0 124116.0 0
2012.0 141273.0 1
2012.0 141288.0 0
2012.0 165554.0 0
2012.0 304413.0 0
2013.0 1073.0 0
2013.0 2631.0 0
2013.0 2650.0 2
2013.0 4695.0 0
2013.0 5126.0 0
2013.0 5130.0 0
2013.0 5174.0 0
2013.0 5181.0 0
2013.0 5186.0 0
2013.0 12780.0 0
2013.0 19327.0 0
2013.0 20177.0 0
2013.0 25142.0 0
2013.0 30838.0 0
2013.0 30847.0 0
2013.0 33883.0 0
2013.0 37212.0 0
2013.0 37235.0 0
2013.0 50983.0 0
2013.0 53770.0 0
2013.0 62610.0 2
2013.0 64645.0 0
2013.0 68995.0 0
2013.0 70384.0 0
2013.0 70392.0 0
2013.0 78027.0 0
2013.0 85983.0 0
2013.0 85992.0 0
2013.0 86443.0 0
2013.0 89025.0 0
2013.0 89027.0 0
2013.0 89036.0 0
2013.0 112487.0 0
2013.0 112512.0 0
2013.0 112515.0 0
2013.0 114215.0 0
2013.0 115115.0 1
2013.0 115943.0 0
2013.0 116816.0 0
2013.0 116818.0 0
2013.0 119292.0 0
2013.0 119298.0 0
2013.0 119311.0 0
2013.0 119314.0 0
2013.0 123595.0 0
2013.0 147021.0 0
2013.0 148173.0 0
2013.0 157531.0 0
2013.0 161632.0 0
2013.0 163759.0 0
2013.0 166316.0 0
2013.0 341543.0 0
2014.0 1754.0 0
2014.0 5173.0 0
2014.0 5914.0 0
2014.0 12762.0 0
2014.0 12785.0 0
2014.0 12798.0 0
2014.0 19551.0 0
2014.0 25112.0 0
2014.0 25134.0 0
2014.0 25149.0 0
2014.0 25150.0 0
2014.0 25171.0 0
2014.0 25176.0 0
2014.0 30832.0 0
2014.0 37126.0 0
2014.0 51011.0 0
2014.0 53770.0 1
2014.0 53772.0 0
2014.0 56626.0 0
2014.0 56631.0 0
2014.0 60622.0 0
2014.0 62616.0 0
2014.0 64645.0 2
2014.0 70964.0 0
2014.0 70968.0 0
2014.0 70994.0 0
2014.0 73268.0 0
2014.0 73589.0 0
2014.0 73593.0 0
2014.0 73595.0 0
2014.0 80890.0 0
2014.0 85987.0 0
2014.0 86411.0 0
2014.0 86423.0 0
2014.0 86428.0 0
2014.0 86429.0 0
2014.0 86431.0 0
2014.0 86436.0 0
2014.0 86444.0 0
2014.0 86446.0 0
2014.0 109170.0 0
2014.0 112521.0 0
2014.0 112525.0 0
2014.0 114164.0 0
2014.0 114226.0 0
2014.0 115115.0 1
2014.0 115943.0 4
2014.0 116817.0 0
2014.0 119388.0 0
2014.0 141281.0 0
2014.0 148170.0 0
2014.0 148173.0 1
2014.0 154638.0 0
2014.0 161849.0 0
2014.0 165210.0 0
2014.0 166108.0 0
2014.0 166220.0 0
2014.0 166316.0 1
2014.0 168619.0 0
2014.0 169042.0 0
2014.0 201011.0 0
2014.0 214025.0 0
2014.0 253252.0 0
2014.0 306897.0 0
2014.0 347242.0 0
2014.0 352109.0 0
2015.0 1767.0 0
2015.0 4690.0 0
2015.0 5147.0 0
2015.0 5148.0 0
2015.0 5171.0 0
2015.0 5190.0 0
2015.0 5906.0 0
2015.0 12798.0 2
2015.0 20078.0 0
2015.0 20177.0 0
2015.0 25303.0 0
2015.0 30834.0 0
2015.0 30836.0 0
2015.0 30838.0 0
2015.0 30888.0 0
2015.0 30891.0 0
2015.0 37121.0 0
2015.0 53771.0 0
2015.0 54993.0 0
2015.0 60622.0 1
2015.0 64567.0 0
2015.0 69009.0 0
2015.0 70973.0 0
2015.0 71074.0 0
2015.0 71084.0 0
2015.0 74768.0 0
2015.0 74821.0 0
2015.0 75228.0 0
2015.0 75230.0 0
2015.0 86412.0 0
2015.0 86414.0 0
2015.0 86428.0 1
2015.0 86432.0 0
2015.0 112486.0 0
2015.0 112493.0 0
2015.0 112511.0 0
2015.0 112524.0 0
2015.0 112526.0 0
2015.0 119300.0 0
2015.0 122969.0 0
2015.0 122979.0 0
2015.0 148232.0 0
2015.0 156467.0 0
2015.0 162569.0 0
2015.0 163755.0 0
2015.0 165124.0 0
2015.0 166105.0 0
2015.0 168619.0 1
2015.0 201228.0 0
2015.0 353118.0 0
2015.0 355204.0 0
2015.0 355205.0 0
2015.0 355206.0 0
2016.0 1737.0 0
2016.0 15834.0 0
2016.0 25164.0 0
2016.0 53778.0 0
2016.0 60607.0 0
2016.0 60608.0 0
2016.0 64645.0 0
2016.0 70337.0 0
2016.0 70350.0 0
2016.0 71081.0 0
2016.0 71084.0 1
2016.0 74821.0 2
2016.0 74826.0 0
2016.0 99633.0 0
2016.0 114831.0 0
2016.0 114832.0 0
2016.0 115104.0 0
2016.0 124117.0 0
2016.0 169042.0 0
2016.0 350465.0 0
2016.0 404741.0 0
2017.0 3810.0 0
2017.0 5137.0 0
2017.0 5173.0 0
2017.0 12553.0 0
2017.0 20073.0 0
2017.0 20075.0 0
2017.0 25136.0 0
2017.0 37276.0 0
2017.0 53778.0 1
2017.0 54988.0 0
2017.0 60645.0 0
2017.0 62611.0 0
2017.0 62617.0 0
2017.0 68991.0 0
2017.0 74821.0 3
2017.0 99631.0 0
2017.0 99632.0 0
2017.0 99633.0 1
2017.0 115095.0 0
2017.0 115115.0 0
2017.0 119300.0 0
2017.0 119446.0 0
2017.0 341863.0 0
2017.0 422733.0 0
2018.0 20081.0 0
2018.0 20169.0 0
2018.0 25176.0 0
2018.0 51011.0 0
2018.0 70397.0 0
2018.0 107668.0 0
2018.0 114262.0 0
2018.0 115115.0 1
2018.0 119314.0 0
2018.0 119447.0 0
2018.0 148226.0 0
2018.0 341911.0 0
2018.0 341912.0 0
2019.0 5124.0 0
2019.0 37258.0 0
2019.0 37352.0 0
2019.0 62619.0 0
2019.0 67215.0 0
2019.0 70964.0 0
2019.0 87080.0 0
2019.0 155896.0 0
2019.0 163740.0 0
2019.0 163759.0 0
2019.0 171735.0 0
2019.0 438994.0 0
2020.0 0.0 3
2020.0 37026.0 0
2020.0 37311.0 0
2020.0 37443.0 0
2020.0 70394.0 0
2020.0 85983.0 0
2020.0 122991.0 0
2021.0 5905.0 0
2021.0 25105.0 0
2021.0 37065.0 0
2021.0 62608.0 0
2021.0 65420.0 0
2021.0 73531.0 0
2021.0 78034.0 0
2021.0 85983.0 1
2021.0 89032.0 0
2021.0 119447.0 0
2021.0 122980.0 0
2021.0 405049.0 0
2022.0 5114.0 0
2022.0 5130.0 0
2022.0 5131.0 0
2022.0 18746.0 0
2022.0 20107.0 0
2022.0 20108.0 0
2022.0 25093.0 0
2022.0 25132.0 0
2022.0 54981.0 0
2022.0 62604.0 0
2022.0 62618.0 0
2022.0 67237.0 0
2022.0 67238.0 0
2022.0 70956.0 0
2022.0 74831.0 0
2022.0 86421.0 0
2022.0 89191.0 0
2022.0 112516.0 0
2022.0 112519.0 0
2022.0 112522.0 0
2022.0 162571.0 0
2022.0 166220.0 0
2022.0 171738.0 0
2023.0 2631.0 0
2023.0 5173.0 0
2023.0 25083.0 0
2023.0 25126.0 0
2023.0 59257.0 0
2023.0 74831.0 1
2023.0 78030.0 0
2023.0 86421.0 1
2023.0 107588.0 0
2023.0 112504.0 0
2023.0 112514.0 0
2023.0 112519.0 1
2023.0 119328.0 0
2023.0 127489.0 0
2023.0 141274.0 0
2024.0 1737.0 0
2024.0 1767.0 0
2024.0 1795.0 0
2024.0 4690.0 0
2024.0 5147.0 0
2024.0 5182.0 0
2024.0 20075.0 0
2024.0 25134.0 0
2024.0 25171.0 0
2024.0 30888.0 0
2024.0 36980.0 0
2024.0 42367.0 0
2024.0 60645.0 0
2024.0 62619.0 0
2024.0 64567.0 0
2024.0 75177.0 0
2024.0 85983.0 0
2024.0 86412.0 0
2024.0 86431.0 0
2024.0 107682.0 0
2024.0 112486.0 0
2024.0 112511.0 0
2024.0 112513.0 0
2024.0 112515.0 0
2024.0 112519.0 1
2024.0 115104.0 0
2024.0 124116.0 0
2024.0 141285.0 0
2024.0 161850.0 0
2024.0 165429.0 0
2024.0 169042.0 0
2024.0 439319.0 0
2010.0 0.0 0
2010.0 3815.0 0
2010.0 4012.0 0
2010.0 4014.0 0
2010.0 9979.0 0
2010.0 18372.0 0
2010.0 33228.0 0
2010.0 35631.0 0
2010.0 35688.0 0
2010.0 38510.0 0
2010.0 76237.0 0
2010.0 90286.0 0
2010.0 90931.0 0
2010.0 96708.0 0
2010.0 101337.0 0
2010.0 101383.0 0
2010.0 101992.0 0
2010.0 102445.0 0
2010.0 131663.0 0
2010.0 131668.0 0
2010.0 155945.0 0
2010.0 161083.0 0
2010.0 163597.0 0
2011.0 18322.0 0
2011.0 18323.0 0
2011.0 32640.0 0
2011.0 32642.0 0
2011.0 39677.0 0
2011.0 39831.0 0
2011.0 46439.0 0
2011.0 90598.0 0
2011.0 90656.0 0
2011.0 90954.0 0
2011.0 101337.0 1
2011.0 101637.0 0
2011.0 101994.0 0
2011.0 143061.0 0
2012.0 4012.0 0
2012.0 15034.0 0
2012.0 18312.0 0
2012.0 18313.0 0
2012.0 18361.0 0
2012.0 18396.0 0
2012.0 18397.0 0
2012.0 28667.0 0
2012.0 28717.0 0
2012.0 35476.0 0
2012.0 41149.0 0
2012.0 41241.0 0
2012.0 55323.0 0
2012.0 90319.0 0
2012.0 90569.0 0
2012.0 90893.0 0
2012.0 101349.0 0
2012.0 101470.0 0
2012.0 101577.0 0
2012.0 110173.0 0
2012.0 137458.0 0
2012.0 137459.0 0
2012.0 137460.0 0
2012.0 137461.0 0
2012.0 137467.0 0
2012.0 155737.0 0
2012.0 157315.0 0
2012.0 157607.0 0
2012.0 162438.0 0
2012.0 163193.0 0
2013.0 3921.0 0
2013.0 9479.0 0
2013.0 9480.0 0
2013.0 10019.0 0
2013.0 10686.0 0
2013.0 10900.0 0
2013.0 11166.0 0
2013.0 11232.0 0
2013.0 11342.0 0
2013.0 18101.0 0
2013.0 18370.0 0
2013.0 18371.0 0
2013.0 18373.0 0
2013.0 18374.0 0
2013.0 18380.0 0
2013.0 18385.0 0
2013.0 18393.0 0
2013.0 18640.0 0
2013.0 37755.0 0
2013.0 38463.0 0
2013.0 39667.0 0
2013.0 41198.0 0
2013.0 41241.0 1
2013.0 90893.0 1
2013.0 90963.0 0
2013.0 101450.0 0
2013.0 101461.0 0
2013.0 101470.0 1
2013.0 101472.0 0
2013.0 101635.0 0
2013.0 121155.0 0
2013.0 131643.0 0
2013.0 137464.0 0
2013.0 142931.0 0
2013.0 340981.0 0
2013.0 341212.0 0
2013.0 347387.0 0
2014.0 0.0 14
2014.0 3842.0 0
2014.0 3910.0 0
2014.0 9480.0 1
2014.0 9488.0 0
2014.0 9712.0 0
2014.0 9802.0 0
2014.0 10896.0 0
2014.0 10897.0 0
2014.0 10899.0 0
2014.0 18101.0 1
2014.0 18351.0 0
2014.0 18397.0 0
2014.0 28615.0 0
2014.0 28658.0 0
2014.0 32655.0 0
2014.0 39680.0 0
2014.0 46257.0 0
2014.0 55592.0 0
2014.0 90548.0 0
2014.0 91231.0 0
2014.0 93978.0 0
2014.0 101317.0 0
2014.0 101439.0 0
2014.0 101483.0 0
2014.0 101577.0 0
2014.0 120987.0 0
2014.0 137783.0 0
2014.0 137791.0 0
2014.0 142929.0 0
2014.0 157041.0 0
2014.0 157161.0 0
2014.0 157244.0 0
2014.0 157452.0 0
2014.0 163131.0 0
2014.0 163590.0 0
2014.0 164168.0 0
2015.0 3856.0 0
2015.0 3910.0 1
2015.0 4810.0 0
2015.0 9488.0 1
2015.0 9501.0 0
2015.0 9550.0 0
2015.0 9578.0 0
2015.0 9602.0 0
2015.0 9635.0 0
2015.0 9641.0 0
2015.0 10033.0 0
2015.0 10305.0 0
2015.0 11059.0 0
2015.0 18318.0 0
2015.0 18322.0 0
2015.0 18638.0 0
2015.0 25712.0 0
2015.0 25757.0 0
2015.0 28623.0 0
2015.0 33209.0 0
2015.0 37110.0 0
2015.0 38690.0 0
2015.0 39262.0 0
2015.0 39900.0 0
2015.0 40064.0 0
2015.0 40272.0 0
2015.0 40815.0 0
2015.0 41226.0 0
2015.0 46504.0 0
2015.0 55624.0 0
2015.0 64929.0 0
2015.0 90310.0 0
2015.0 90319.0 0
2015.0 90334.0 0
2015.0 90336.0 0
2015.0 90343.0 0
2015.0 90524.0 0
2015.0 101315.0 0
2015.0 101346.0 0
2015.0 101367.0 0
2015.0 101372.0 0
2015.0 101430.0 0
2015.0 101434.0 0
2015.0 101436.0 0
2015.0 101438.0 0
2015.0 101440.0 0
2015.0 101446.0 0
2015.0 101466.0 0
2015.0 101475.0 0
2015.0 101477.0 0
2015.0 101577.0 1
2015.0 101992.0 0
2015.0 131637.0 0
2015.0 131638.0 0
2015.0 137477.0 0
2015.0 142980.0 0
2015.0 153234.0 0
2015.0 157041.0 2
2015.0 162423.0 0
2015.0 165216.0 0
2015.0 167428.0 0
2015.0 167591.0 0
2015.0 168039.0 0
2015.0 168052.0 0
2015.0 341128.0 0
2015.0 353806.0 0
2016.0 4817.0 0
2016.0 4827.0 0
2016.0 9535.0 0
2016.0 10050.0 0
2016.0 10069.0 0
2016.0 10260.0 0
2016.0 10285.0 0
2016.0 10626.0 0
2016.0 18415.0 0
2016.0 26648.0 0
2016.0 28667.0 0
2016.0 28681.0 0
2016.0 33282.0 0
2016.0 35660.0 0
2016.0 35663.0 0
2016.0 40064.0 1
2016.0 40272.0 1
2016.0 41226.0 1
2016.0 46334.0 0
2016.0 46421.0 0
2016.0 55624.0 1
2016.0 56953.0 0
2016.0 62827.0 0
2016.0 76238.0 0
2016.0 84616.0 0
2016.0 90310.0 1
2016.0 90319.0 1
2016.0 90324.0 0
2016.0 90334.0 2
2016.0 90336.0 2
2016.0 90343.0 1
2016.0 90372.0 0
2016.0 90446.0 0
2016.0 91493.0 0
2016.0 91601.0 0
2016.0 93929.0 0
2016.0 101436.0 1
2016.0 101437.0 0
2016.0 101438.0 1
2016.0 101440.0 1
2016.0 101472.0 0
2016.0 121155.0 0
2016.0 150574.0 0
2016.0 157607.0 0
2016.0 162457.0 0
2016.0 163448.0 0
2016.0 163602.0 0
2016.0 167424.0 0
2016.0 167590.0 0
2016.0 168054.0 0
2016.0 171012.0 0
2016.0 172953.0 0
2016.0 340858.0 0
2016.0 350829.0 0
2017.0 0.0 3
2017.0 4091.0 0
2017.0 9550.0 0
2017.0 9758.0 0
2017.0 9813.0 0
2017.0 9819.0 0
2017.0 10069.0 1
2017.0 10721.0 0
2017.0 18321.0 0
2017.0 18333.0 0
2017.0 33226.0 0
2017.0 33288.0 0
2017.0 38674.0 0
2017.0 45830.0 0
2017.0 46509.0 0
2017.0 56953.0 1
2017.0 64929.0 0
2017.0 66066.0 0
2017.0 76238.0 2
2017.0 84661.0 0
2017.0 90324.0 1
2017.0 90533.0 0
2017.0 90848.0 0
2017.0 90850.0 0
2017.0 90851.0 0
2017.0 94003.0 0
2017.0 101330.0 0
2017.0 101535.0 0
2017.0 102512.0 0
2017.0 161890.0 0
2017.0 162417.0 0
2017.0 168743.0 0
2018.0 0.0 4
2018.0 4111.0 0
2018.0 9477.0 0
2018.0 9511.0 0
2018.0 9758.0 1
2018.0 9819.0 1
2018.0 10614.0 0
2018.0 10721.0 1
2018.0 11080.0 0
2018.0 11246.0 0
2018.0 18322.0 0
2018.0 18415.0 0
2018.0 25581.0 0
2018.0 25688.0 0
2018.0 28740.0 0
2018.0 84608.0 0
2018.0 87852.0 0
2018.0 90343.0 0
2018.0 90405.0 0
2018.0 90486.0 0
2018.0 101453.0 0
2018.0 101997.0 0
2018.0 120942.0 0
2018.0 120974.0 0
2018.0 120988.0 0
2018.0 131648.0 0
2018.0 137458.0 0
2018.0 156038.0 0
2018.0 161890.0 1
2018.0 162438.0 0
2018.0 163712.0 0
2019.0 0.0 1
2019.0 605.0 0
2019.0 4001.0 0
2019.0 9819.0 1
2019.0 10338.0 0
2019.0 10530.0 0
2019.0 10721.0 1
2019.0 11247.0 0
2019.0 15007.0 0
2019.0 28821.0 0
2019.0 35631.0 0
2019.0 39900.0 0
2019.0 41283.0 0
2019.0 43213.0 0
2019.0 45830.0 0
2019.0 46522.0 0
2019.0 55602.0 0
2019.0 56953.0 0
2019.0 56958.0 0
2019.0 66042.0 0
2019.0 84594.0 0
2019.0 90310.0 0
2019.0 90575.0 0
2019.0 90636.0 0
2019.0 90706.0 0
2019.0 90824.0 0
2019.0 90856.0 0
2019.0 90860.0 0
2019.0 101375.0 0
2019.0 101471.0 0
2019.0 101985.0 0
2019.0 101998.0 0
2019.0 120902.0 0
2019.0 120988.0 1
2019.0 120992.0 0
2019.0 131637.0 0
2019.0 137486.0 0
2019.0 143075.0 0
2019.0 150583.0 0
2019.0 157041.0 0
2019.0 161890.0 1
2019.0 161897.0 0
2019.0 162452.0 0
2019.0 163712.0 1
2019.0 170055.0 0
2019.0 345773.0 0
2020.0 0.0 3
2020.0 4091.0 0
2020.0 4847.0 0
2020.0 10606.0 0
2020.0 10679.0 0
2020.0 10686.0 0
2020.0 10721.0 1
2020.0 10910.0 0
2020.0 18333.0 0
2020.0 18340.0 0
2020.0 25611.0 0
2020.0 28652.0 0
2020.0 39826.0 0
2020.0 39972.0 0
2020.0 41283.0 2
2020.0 57014.0 0
2020.0 79006.0 0
2020.0 84594.0 1
2020.0 90824.0 1
2020.0 93983.0 0
2020.0 101330.0 0
2020.0 101338.0 0
2020.0 101455.0 0
2020.0 101471.0 1
2020.0 101997.0 0
2020.0 120974.0 0
2020.0 120988.0 1
2020.0 157244.0 0
2020.0 161583.0 0
2020.0 161890.0 1
2020.0 163125.0 0
2020.0 163712.0 2
2021.0 0.0 2
2021.0 9519.0 0
2021.0 9667.0 0
2021.0 25764.0 0
2021.0 35551.0 0
2021.0 41283.0 1
2021.0 64880.0 0
2021.0 90310.0 0
2021.0 101439.0 0
2021.0 101491.0 0
2021.0 131637.0 0
2021.0 158173.0 0
2021.0 345598.0 0
2022.0 3815.0 0
2022.0 3829.0 0
2022.0 3862.0 0
2022.0 3864.0 0
2022.0 3865.0 0
2022.0 3871.0 0
2022.0 4007.0 0
2022.0 4033.0 0
2022.0 4131.0 0
2022.0 4136.0 0
2022.0 4145.0 0
2022.0 4151.0 0
2022.0 10337.0 0
2022.0 18328.0 0
2022.0 18389.0 0
2022.0 39860.0 0
2022.0 39873.0 0
2022.0 46340.0 0
2022.0 46523.0 0
2022.0 56963.0 0
2022.0 64929.0 0
2022.0 66074.0 0
2022.0 84589.0 0
2022.0 90310.0 1
2022.0 90319.0 0
2022.0 91601.0 0
2022.0 101984.0 0
2022.0 137469.0 0
2022.0 137617.0 0
2022.0 142944.0 0
2022.0 158150.0 0
2022.0 163461.0 0
2022.0 167427.0 0
2022.0 167428.0 0
2022.0 343513.0 0
2022.0 344768.0 0
2023.0 10033.0 0
2023.0 10721.0 0
2023.0 11259.0 0
2023.0 11351.0 0
2023.0 18313.0 0
2023.0 18381.0 0
2023.0 18415.0 0
2023.0 28641.0 0
2023.0 32625.0 0
2023.0 37778.0 0
2023.0 38560.0 0
2023.0 39678.0 0
2023.0 41283.0 0
2023.0 55340.0 0
2023.0 55565.0 0
2023.0 90567.0 0
2023.0 90899.0 0
2023.0 90931.0 0
2023.0 101330.0 0
2023.0 101345.0 0
2023.0 101995.0 0
2023.0 101996.0 0
2023.0 150583.0 0
2023.0 153241.0 0
2023.0 340858.0 0
2024.0 0.0 1
2024.0 3862.0 0
2024.0 3864.0 0
2024.0 4080.0 0
2024.0 4131.0 0
2024.0 4151.0 0
2024.0 9501.0 0
2024.0 9550.0 0
2024.0 10033.0 1
2024.0 10743.0 0
2024.0 18313.0 1
2024.0 18381.0 2
2024.0 33146.0 0
2024.0 33282.0 0
2024.0 39738.0 0
2024.0 39825.0 0
2024.0 55343.0 0
2024.0 90302.0 0
2024.0 90310.0 0
2024.0 90319.0 0
2024.0 90405.0 0
2024.0 93942.0 0
2024.0 101334.0 0
2024.0 120987.0 0
2024.0 158131.0 0
2024.0 171613.0 0
2024.0 341077.0 0
2024.0 367825.0 0
2009.0 11072.0 0
2010.0 0.0 0
2010.0 11991.0 0
2010.0 12991.0 0
2010.0 13000.0 0
2010.0 19556.0 0
2010.0 26893.0 0
2010.0 26902.0 0
2010.0 29137.0 0
2010.0 29172.0 0
2010.0 31381.0 0
2010.0 80175.0 0
2010.0 98503.0 0
2010.0 138003.0 0
2010.0 155704.0 0
2010.0 163153.0 0
2011.0 0.0 45
2011.0 9701.0 0
2011.0 26902.0 1
2011.0 29137.0 2
2011.0 29152.0 0
2011.0 110774.0 0
2011.0 123774.0 0
2011.0 123776.0 0
2011.0 123777.0 0
2011.0 144935.0 0
2011.0 161874.0 0
2011.0 163153.0 3
2011.0 169531.0 0
2011.0 340652.0 0
2011.0 343210.0 0
2012.0 10053.0 0
2012.0 15792.0 0
2012.0 31437.0 0
2012.0 98611.0 0
2012.0 170408.0 0
2013.0 0.0 36
2013.0 9666.0 0
2013.0 11517.0 0
2013.0 11909.0 0
2013.0 20243.0 0
2013.0 26926.0 0
2013.0 31327.0 0
2013.0 31511.0 0
2013.0 98768.0 0
2013.0 110762.0 0
2013.0 110772.0 0
2013.0 123777.0 0
2013.0 136811.0 0
2013.0 142038.0 0
2013.0 144935.0 0
2013.0 162104.0 0
2013.0 169533.0 0
2013.0 171030.0 0
2014.0 11478.0 0
2014.0 29137.0 0
2014.0 31327.0 2
2014.0 31390.0 0
2014.0 98583.0 0
2014.0 98612.0 0
2014.0 170408.0 0
2014.0 351708.0 0
2015.0 11478.0 1
2015.0 12370.0 0
2015.0 12466.0 0
2015.0 12467.0 0
2015.0 29137.0 1
2015.0 29162.0 0
2015.0 29163.0 0
2015.0 31404.0 0
2015.0 31438.0 0
2015.0 80103.0 0
2015.0 98502.0 0
2015.0 98542.0 0
2015.0 98544.0 0
2015.0 98545.0 0
2015.0 98742.0 0
2015.0 106089.0 0
2015.0 139291.0 0
2015.0 144637.0 0
2015.0 163308.0 0
2015.0 167912.0 0
2015.0 169108.0 0
2016.0 11266.0 0
2016.0 21785.0 0
2016.0 29159.0 0
2016.0 31437.0 0
2016.0 98542.0 1
2016.0 98544.0 1
2016.0 98545.0 1
2016.0 98717.0 0
2016.0 98745.0 0
2016.0 150875.0 0
2016.0 171880.0 0
2016.0 278969.0 0
2016.0 343210.0 0
2016.0 347140.0 0
2017.0 12214.0 0
2017.0 43808.0 0
2017.0 98532.0 0
2017.0 98545.0 2
2017.0 103543.0 0
2017.0 110627.0 0
2017.0 139287.0 0
2017.0 144637.0 0
2017.0 168952.0 0
2018.0 12021.0 0
2018.0 12214.0 1
2018.0 12219.0 0
2018.0 12226.0 0
2018.0 13000.0 0
2018.0 31521.0 0
2018.0 98542.0 0
2018.0 98725.0 0
2018.0 110711.0 0
2018.0 116213.0 0
2018.0 123779.0 0
2018.0 162368.0 0
2019.0 11866.0 0
2019.0 13000.0 2
2019.0 15792.0 0
2019.0 17550.0 0
2019.0 26907.0 0
2019.0 31471.0 0
2019.0 98542.0 1
2019.0 98544.0 0
2019.0 98545.0 0
2019.0 106095.0 0
2019.0 110676.0 0
2019.0 110705.0 0
2019.0 110707.0 0
2019.0 110788.0 0
2019.0 163308.0 0
2020.0 15794.0 0
2020.0 20225.0 0
2020.0 31328.0 0
2020.0 31437.0 0
2020.0 31471.0 1
2020.0 98544.0 1
2020.0 98727.0 0
2020.0 110676.0 1
2020.0 123777.0 0
2020.0 130062.0 0
2020.0 136811.0 0
2020.0 163308.0 1
2021.0 15792.0 0
2021.0 29159.0 0
2021.0 31471.0 1
2021.0 123777.0 1
2021.0 139287.0 0
2021.0 139291.0 0
2021.0 163961.0 0
2022.0 10053.0 0
2022.0 15794.0 0
2022.0 29152.0 0
2022.0 31381.0 0
2022.0 43806.0 0
2022.0 98727.0 0
2022.0 98779.0 0
2022.0 98802.0 0
2022.0 156399.0 0
2022.0 163942.0 0
2022.0 169531.0 0
2022.0 356415.0 0
2022.0 356512.0 0
2023.0 11236.0 0
2023.0 11266.0 0
2023.0 12466.0 0
2023.0 26940.0 0
2023.0 31437.0 0
2023.0 69055.0 0
2023.0 150206.0 0
2024.0 12236.0 0
2024.0 12466.0 1
2024.0 15794.0 0
2024.0 29152.0 0
2024.0 116213.0 0
2024.0 138003.0 0
2024.0 144935.0 0
2024.0 144937.0 0
2024.0 150206.0 1
2024.0 157146.0 0
2024.0 356415.0 0
2009.0 150792.0 0
2010.0 0.0 0
2010.0 12557.0 0
2010.0 12756.0 0
2010.0 12768.0 0
2010.0 15449.0 0
2010.0 31864.0 0
2010.0 32318.0 0
2010.0 33665.0 0
2010.0 37764.0 0
2010.0 38426.0 0
2010.0 38777.0 0
2010.0 44254.0 0
2010.0 47782.0 0
2010.0 48048.0 0
2010.0 48060.0 0
2010.0 50300.0 0
2010.0 50306.0 0
2010.0 51469.0 0
2010.0 54086.0 0
2010.0 54092.0 0
2010.0 59598.0 0
2010.0 63508.0 0
2010.0 81625.0 0
2010.0 83014.0 0
2010.0 83029.0 0
2010.0 83356.0 0
2010.0 84049.0 0
2010.0 84743.0 0
2010.0 85997.0 0
2010.0 89446.0 0

In [89]:
temp[(temp['Count_of_violations']>5) & (temp['sam_id']!=0)]

,Neighbourhood,Year,sam_id,Count_of_violations,prev_year_violation
3,Allston,2010.0,1737.0,6,0
127,Allston,2013.0,25142.0,7,0
171,Allston,2014.0,12785.0,6,0
248,Allston,2015.0,30891.0,13,0
315,Allston,2017.0,53778.0,7,1
...,...,...,...,...,...
10979,Roxbury,2018.0,75983.0,6,3
11405,Roxbury,2021.0,162187.0,7,3
12552,South End,2014.0,22161.0,6,0
12585,South End,2015.0,15100.0,8,0
12723,South End,2018.0,371800.0,8,0

In [90]:
temp[(temp['prev_year_violation']>5) & (temp['sam_id']!=0)]

,Neighbourhood,Year,sam_id,Count_of_violations,prev_year_violation
3031,Dorchester,2013.0,72902.0,1,6
3564,Dorchester,2015.0,94063.0,1,12
3645,Dorchester,2015.0,141452.0,1,6
3945,Dorchester,2017.0,129629.0,1,14
4766,Dorchester,2024.0,35378.0,2,6
5655,East Boston,2011.0,85759.0,2,7
5681,East Boston,2011.0,105876.0,1,6
7223,Hyde Park,2011.0,96423.0,1,7
8299,Mattapan,2012.0,16237.0,1,10
10138,Roxbury,2012.0,70301.0,1,8
10168,Roxbury,2012.0,98371.0,1,7
10211,Roxbury,2012.0,143328.0,12,6
10522,Roxbury,2014.0,151037.0,1,8
10761,Roxbury,2015.0,165614.0,1,9
11093,Roxbury,2019.0,75983.0,1,6
12631,South End,2016.0,15100.0,1,8

In [91]:
temp[temp['sam_id']==15100.0]

      Neighbourhood    Year   sam_id  Count_of_violations  prev_year_violation
12585     South End  2015.0  15100.0                    8                    0
12631     South End  2016.0  15100.0                    1                    8

## Number of Buildings

In [93]:
sam_adds = pd.read_csv("Geolocated_SAMAddresses.csv")

C:\Users\adity\AppData\Local\Temp\ipykernel_95892\1067669544.py:1: DtypeWarning: Columns (7,9,10,18,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  sam_adds = pd.read_csv("Geolocated_SAMAddresses.csv")

In [94]:
sam_adds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400197 entries, 0 to 400196
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   X                     400197 non-null  float64
 1   Y                     400197 non-null  float64
 2   OBJECTID              400197 non-null  int64
 3   SAM_ADDRESS_ID        400197 non-null  int64
 4   BUILDING_ID           400197 non-null  int64
 5   RELATIONSHIP_TYPE     400197 non-null  int64
 6   FULL_ADDRESS          400197 non-null  object
 7   STREET_NUMBER         400197 non-null  object
 8   IS_RANGE              400197 non-null  int64
 9   RANGE_FROM            25926 non-null   object
 10  RANGE_TO              25926 non-null   object
 11  UNIT                  268565 non-null  object
 12  FULL_STREET_NAME      400189 non-null  object
 13  STREET_ID             400193 non-null  float64
 14  STREET_PREFIX         21391 non-null   object
 15  STREET_BODY           400189 non-null  object
 16  STREET_SUFFIX_ABBR    396113 non-null  object
 17  STREET_FULL_SUFFIX    396113 non-null  object
 18  STREET_SUFFIX_DIR     1009 non-null    object
 19  STREET_NUMBER_SORT    400197 non-null  int64
 20  MAILING_NEIGHBORHOOD  400197 non-null  object
 21  ZIP_CODE              400197 non-null  int64
 22  X_COORD               400197 non-null  float64
 23  Y_COORD               400197 non-null  float64
 24  SAM_STREET_ID         400193 non-null  float64
 25  WARD                  400197 non-null  int64
 26  PRECINCT_WARD         400197 non-null  int64
 27  PARCEL                400197 non-null  object
 28  created_date          243000 non-null  object
 29  last_edited_date      335844 non-null  object
 30  Latitude              396042 non-null  float64
 31  Longitude             396042 non-null  float64
dtypes: float64(8), int64(9), object(15)
memory usage: 97.7+ MB

In [99]:
n_zip

   Zip Code            Neighbourhood
0     02021                   Canton
1     02108              Beacon Hill
2     02109                 Downtown
3     02110                 Downtown
4     02111                Chinatown
5     02113                North End
6     02114                 Downtown
7     02115           Fenway/Kenmore
8     02116                 Back Bay
9     02117                 Back Bay
10    02118                South End
11    02119                  Roxbury
12    02120             Mission Hill
13    02120                  Roxbury
14    02121                  Roxbury
15    02122               Dorchester
16    02123                 Back Bay
17    02124               Dorchester
18    02125               Dorchester
19    02126                 Mattapan
20    02127             South Boston
21    02128              East Boston
22    02129              Charlestown
23    02130            Jamaica Plain
24    02131               Roslindale
25    02132             West Roxbury
26    02133                 Back Bay
27    02134                  Allston
28    02135                 Brighton
29    02136                Hyde Park
30    02151                   Revere
31    02152                 Winthrop
32    02163                 Brighton
33    02199                 Back Bay
34    02210  South Boston Waterfront
35    02215           Fenway/Kenmore
36    02228              East Boston
37    02467            Chestnut Hill

In [100]:
sam_adds['ZIP_CODE'] = sam_adds['ZIP_CODE'].astype(str)
sam_adds['ZIP_CODE'] = sam_adds['ZIP_CODE'].apply(lambda x: "0"+x)

In [101]:
sam_adds = df = pd.merge(sam_adds,n_zip, left_on='ZIP_CODE', right_on='Zip Code', how='left')

In [116]:
sam_adds_bldgs = sam_adds[['BUILDING_ID','Zip Code','Neighbourhood']]

In [117]:
sam_adds_bldgs = sam_adds_bldgs.drop_duplicates()

In [152]:
no_of_bldgs = sam_adds_bldgs.groupby(['Neighbourhood']).size()

In [153]:
no_of_bldgs =no_of_bldgs.reset_index()
no_of_bldgs.columns = ['Neighbourhood','no_of_bldgs']

In [154]:
no_of_bldgs

              Neighbourhood  no_of_bldgs
0                   Allston         2077
1                  Back Bay         2102
2               Beacon Hill          652
3                  Brighton         5310
4               Charlestown         2795
5             Chestnut Hill          216
6                 Chinatown          336
7                Dorchester        17587
8                  Downtown         1449
9               East Boston         6062
10           Fenway/Kenmore         1959
11                Hyde Park         7700
12            Jamaica Plain         6149
13                 Mattapan         4154
14             Mission Hill         1297
15                North End          825
16               Roslindale         6717
17                  Roxbury         8825
18             South Boston         5959
19  South Boston Waterfront          278
20                South End         2371
21             West Roxbury         8478
22                 Winthrop            1

In [155]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407534 entries, 0 to 407533
Data columns (total 34 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   X                     407534 non-null  float64
 1   Y                     407534 non-null  float64
 2   OBJECTID              407534 non-null  int64
 3   SAM_ADDRESS_ID        407534 non-null  int64
 4   BUILDING_ID           407534 non-null  int64
 5   RELATIONSHIP_TYPE     407534 non-null  int64
 6   FULL_ADDRESS          407534 non-null  object
 7   STREET_NUMBER         407534 non-null  object
 8   IS_RANGE              407534 non-null  int64
 9   RANGE_FROM            26370 non-null   object
 10  RANGE_TO              26370 non-null   object
 11  UNIT                  273487 non-null  object
 12  FULL_STREET_NAME      407526 non-null  object
 13  STREET_ID             407530 non-null  float64
 14  STREET_PREFIX         21656 non-null   object
 15  STREET_BODY           407526 non-null  object
 16  STREET_SUFFIX_ABBR    403450 non-null  object
 17  STREET_FULL_SUFFIX    403450 non-null  object
 18  STREET_SUFFIX_DIR     1009 non-null    object
 19  STREET_NUMBER_SORT    407534 non-null  int64
 20  MAILING_NEIGHBORHOOD  407534 non-null  object
 21  ZIP_CODE              407534 non-null  object
 22  X_COORD               407534 non-null  float64
 23  Y_COORD               407534 non-null  float64
 24  SAM_STREET_ID         407530 non-null  float64
 25  WARD                  407534 non-null  int64
 26  PRECINCT_WARD         407534 non-null  int64
 27  PARCEL                407534 non-null  object
 28  created_date          246640 non-null  object
 29  last_edited_date      342941 non-null  object
 30  Latitude              403337 non-null  float64
 31  Longitude             403337 non-null  float64
 32  Zip Code              406847 non-null  object
 33  Neighbourhood         406847 non-null  object
dtypes: float64(8), int64(8), object(18)
memory usage: 105.7+ MB

In [121]:
census = pd.read_csv('census.csv')

In [156]:
census.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 34 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Neighbourhood                                                 24 non-null     object
 1   Total:                                                        24 non-null     int64
 2   White alone                                                   24 non-null     int64
 3   Black or African American alone                               24 non-null     int64
 4   Hispanic or Latino                                            24 non-null     int64
 5   Asian, Native Hawaiian and Pacific Islander alone, all ages   24 non-null     int64
 6   Other Races or Multiple Races,  all ages                      24 non-null     int64
 7   Total:.1                                                      24 non-null     int64
 8   White alone.1                                                 24 non-null     int64
 9   Black or African American alone.1                             24 non-null     int64
 10  Hispanic or Latino.1                                          24 non-null     int64
 11  Asian, Native Hawaiian and Pacific Islander alone, aged 18+   24 non-null     int64
 12  Other Races or Multiple Races, aged 18+                       24 non-null     int64
 13  Total: aged 0-17                                              24 non-null     int64
 14  White alone, aged 0-17                                        24 non-null     int64
 15  Black or African American alone, aged 0-17                    24 non-null     int64
 16  Hispanic or Latino, aged 0-17                                 24 non-null     int64
 17  Asian, Native Hawaiian and Pacific Islander alone, aged 0-17  24 non-null     int64
 18  Other Races or Multiple Races, aged 0-17                      24 non-null     int64
 19  household population                                          24 non-null     int64
 20  Total:.2                                                      24 non-null     int64
 21  Institutionalized population:                                 24 non-null     int64
 22  Correctional facilities for adults                            24 non-null     int64
 23  Juvenile facilities                                           24 non-null     int64
 24  Nursing facilities/Skilled-nursing facilities                 24 non-null     int64
 25  Other institutional facilities                                24 non-null     int64
 26  Noninstitutionalized population:                              24 non-null     int64
 27  College/University student housing                            24 non-null     int64
 28  Military quarters                                             24 non-null     int64
 29  Other noninstitutional facilities                             24 non-null     int64
 30  Total:.3                                                      24 non-null     int64
 31  Occupied                                                      24 non-null     int64
 32  Vacant                                                        24 non-null     int64
 33  household size                                                24 non-null     float64
dtypes: float64(1), int64(32), object(1)
memory usage: 6.5+ KB

In [157]:
no_of_bldgs = pd.merge(no_of_bldgs, census[['Neighbourhood','Total:.3']], left_on='Neighbourhood', right_on='Neighbourhood', how='left')

In [158]:
no_of_bldgs.columns = ['Neighbourhood', 'no_of_bldgs_student', 'no_of_bldgs_census']

In [159]:
no_of_bldgs.dropna(inplace=True)

In [160]:
no_of_bldgs['% of student occupied buildings'] = no_of_bldgs['no_of_bldgs_student']*100/no_of_bldgs['no_of_bldgs_census']

Calculating number of bldgs occupied by students versus total number of buildings

In [161]:
no_of_bldgs

,Neighbourhood,no_of_bldgs_student,no_of_bldgs_census,% of student occupied buildings
0,Allston,2077,10748.0,19.324525
1,Back Bay,2102,11524.0,18.240194
2,Beacon Hill,652,6037.0,10.800066
3,Brighton,5310,23653.0,22.449584
4,Charlestown,2795,9525.0,29.343832
6,Chinatown,336,3272.0,10.268949
7,Dorchester,17587,47965.0,36.666319
8,Downtown,1449,6604.0,21.941248
9,East Boston,6062,18016.0,33.647869
10,Fenway/Kenmore,1959,14991.0,13.067841
11,Hyde Park,7700,13049.0,59.008353
12,Jamaica Plain,6149,18547.0,33.153610
13,Mattapan,4154,9347.0,44.442067
14,Mission Hill,1297,6955.0,18.648454
15,North End,825,6832.0,12.075527
16,Roslindale,6717,12277.0,54.712063
17,Roxbury,8825,21687.0,40.692581
18,South Boston,5959,19140.0,31.133751
19,South Boston Waterfront,278,4622.0,6.014712
20,South End,2371,17598.0,13.473122
21,West Roxbury,8478,14070.0,60.255864

In [166]:
no_of_bldgs = pd.melt(
    no_of_bldgs,
    id_vars=["Neighbourhood", "% of student occupied buildings"],
    value_vars=["no_of_bldgs_student", "no_of_bldgs_census"],
    var_name="Building Type",
    value_name="Count"
)

In [167]:
no_of_bldgs.to_csv('No_of_bldgs.csv',index=False)

In [165]:
pd.melt(
    no_of_bldgs,
    id_vars=["Neighbourhood", "% of student occupied buildings"],
    value_vars=["no_of_bldgs_student", "no_of_bldgs_census"],
    var_name="Building Type",
    value_name="Count"
)

,Neighbourhood,% of student occupied buildings,Building Type,Count
0,Allston,19.324525,no_of_bldgs_student,2077.0
1,Back Bay,18.240194,no_of_bldgs_student,2102.0
2,Beacon Hill,10.800066,no_of_bldgs_student,652.0
3,Brighton,22.449584,no_of_bldgs_student,5310.0
4,Charlestown,29.343832,no_of_bldgs_student,2795.0
5,Chinatown,10.268949,no_of_bldgs_student,336.0
6,Dorchester,36.666319,no_of_bldgs_student,17587.0
7,Downtown,21.941248,no_of_bldgs_student,1449.0
8,East Boston,33.647869,no_of_bldgs_student,6062.0
9,Fenway/Kenmore,13.067841,no_of_bldgs_student,1959.0
10,Hyde Park,59.008353,no_of_bldgs_student,7700.0
11,Jamaica Plain,33.153610,no_of_bldgs_student,6149.0
12,Mattapan,44.442067,no_of_bldgs_student,4154.0
13,Mission Hill,18.648454,no_of_bldgs_student,1297.0
14,North End,12.075527,no_of_bldgs_student,825.0
15,Roslindale,54.712063,no_of_bldgs_student,6717.0
16,Roxbury,40.692581,no_of_bldgs_student,8825.0
17,South Boston,31.133751,no_of_bldgs_student,5959.0
18,South Boston Waterfront,6.014712,no_of_bldgs_student,278.0
19,South End,13.473122,no_of_bldgs_student,2371.0
20,West Roxbury,60.255864,no_of_bldgs_student,8478.0
21,Allston,19.324525,no_of_bldgs_census,10748.0
22,Back Bay,18.240194,no_of_bldgs_census,11524.0
23,Beacon Hill,10.800066,no_of_bldgs_census,6037.0
24,Brighton,22.449584,no_of_bldgs_census,23653.0
25,Charlestown,29.343832,no_of_bldgs_census,9525.0
26,Chinatown,10.268949,no_of_bldgs_census,3272.0
27,Dorchester,36.666319,no_of_bldgs_census,47965.0
28,Downtown,21.941248,no_of_bldgs_census,6604.0
29,East Boston,33.647869,no_of_bldgs_census,18016.0
30,Fenway/Kenmore,13.067841,no_of_bldgs_census,14991.0
31,Hyde Park,59.008353,no_of_bldgs_census,13049.0
32,Jamaica Plain,33.153610,no_of_bldgs_census,18547.0
33,Mattapan,44.442067,no_of_bldgs_census,9347.0
34,Mission Hill,18.648454,no_of_bldgs_census,6955.0
35,North End,12.075527,no_of_bldgs_census,6832.0
36,Roslindale,54.712063,no_of_bldgs_census,12277.0
37,Roxbury,40.692581,no_of_bldgs_census,21687.0
38,South Boston,31.133751,no_of_bldgs_census,19140.0
39,South Boston Waterfront,6.014712,no_of_bldgs_census,4622.0
40,South End,13.473122,no_of_bldgs_census,17598.0
41,West Roxbury,60.255864,no_of_bldgs_census,14070.0