In [2]:
import pandas as pd
import glob

all_files = glob.glob("./*.csv")

In [4]:
combined_df = pd.concat((pd.read_csv(file) for file in all_files), ignore_index=True)

/var/folders/s9/tjqjhlhs57q4zp00qz4178gc0000gn/T/ipykernel_28918/2762595841.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_df = pd.concat((pd.read_csv(file) for file in all_files), ignore_index=True)
/var/folders/s9/tjqjhlhs57q4zp00qz4178gc0000gn/T/ipykernel_28918/2762595841.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_df = pd.concat((pd.read_csv(file) for file in all_files), ignore_index=True)
/var/folders/s9/tjqjhlhs57q4zp00qz4178gc0000gn/T/ipykernel_28918/2762595841.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_df = pd.concat((pd.read_csv(file) for file in all_files), ignore_index=True)
/var/folders/s9/tjqjhlhs57q4zp00qz4178gc0000gn/T/ipykernel_28918/2762595841.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_df = pd.concat((pd.read_csv(file) for file in all_files), ignore_index=True)
/var/folders/s9/tjqjhlhs57q4zp00qz4178gc0000gn/T/ipykernel_28918/2762595841.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_df = pd.concat((pd.read_csv(file) for file in all_files), ignore_index=True)
/var/folders/s9/tjqjhlhs57q4zp00qz4178gc0000gn/T/ipykernel_28918/2762595841.py:1: DtypeWarning: Columns (13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_df = pd.concat((pd.read_csv(file) for file in all_files), ignore_index=True)
/var/folders/s9/tjqjhlhs57q4zp00qz4178gc0000gn/T/ipykernel_28918/2762595841.py:1: DtypeWarning: Columns (13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_df = pd.concat((pd.read_csv(file) for file in all_files), ignore_index=True)
/var/folders/s9/tjqjhlhs57q4zp00qz4178gc0000gn/T/ipykernel_28918/2762595841.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_df = pd.concat((pd.read_csv(file) for file in all_files), ignore_index=True)

In [5]:
combined_df = pd.concat((pd.read_csv(file, low_memory=False) for file in all_files), ignore_index=True)

In [6]:
combined_df.to_csv('combined_file.csv', index=False)

In [7]:
data = pd.read_csv('combined_file.csv')
data.head(15)

/var/folders/s9/tjqjhlhs57q4zp00qz4178gc0000gn/T/ipykernel_28918/3649526037.py:1: DtypeWarning: Columns (13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('combined_file.csv')

,case_enquiry_id,open_dt,sla_target_dt,closed_dt,on_time,case_status,closure_reason,case_title,subject,reason,...,neighborhood,neighborhood_services_district,ward,precinct,location_street_name,location_zipcode,latitude,longitude,geom_4326,source
0,101003148265,2020-01-01 00:07:00,2020-01-13 03:30:00,2020-01-20 06:43:10,OVERDUE,Closed,Case Closed. Closed date : 2020-01-20 11:43:10...,Park Lights - Doherty Playground (BPRD),Parks & Recreation Department,Park Maintenance & Safety,...,Charlestown,2,2,0207,INTERSECTION S Quincy Pl & Saint Martin St,NaN,42.382987,-71.067828,0101000020E6100000ADA5774957C451C01A77A6B30531...,Citizens Connect App
1,101003148266,2020-01-01 00:54:48,2020-01-01 00:54:48,2020-01-02 01:11:49,OVERDUE,Closed,Case Closed. Closed date : 2020-01-02 06:11:49...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,Dorchester,8,Ward 17,1702,85 Bloomfield St,2124.0,42.298900,-71.069541,0101000020E6100000E9E56F5A73C451C07E7212574226...,Citizens Connect App
2,101003148268,2020-01-01 01:14:13,2020-01-03 03:30:00,2020-01-01 10:05:46,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 15:05:46...,Requests for Street Cleaning,Public Works Department,Street Cleaning,...,South End,6,Ward 9,0901,423 Shawmut Ave,2118.0,42.340130,-71.074291,0101000020E6100000E2300A2DC1C451C0AAFE665D892B...,Citizens Connect App
3,101003148269,2020-01-01 01:19:00,2020-01-03 03:30:00,2020-01-02 01:10:56,ONTIME,Closed,Case Closed. Closed date : 2020-01-02 06:10:56...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,Roxbury,13,Ward 12,1201,6 Moreland St,2119.0,42.325960,-71.082761,0101000020E61000006A0602F34BC551C0EB78EE0AB929...,Constituent Call
4,101003148271,2020-01-01 02:02:00,2020-01-03 03:30:00,2020-01-01 02:07:17,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 07:07:17...,Missed Trash: District 1B,Public Works Department,Sanitation,...,Beacon Hill,14,Ward 5,0503,25-29 Charles St,2114.0,42.356920,-71.069650,0101000020E61000001AD6442775C451C0A731108AAF2D...,Constituent Call
5,101003148272,2020-01-01 02:04:00,2020-01-03 03:30:00,2020-01-01 03:11:52,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 08:11:52...,Missed Trash: District 1A,Public Works Department,Sanitation,...,Charlestown,2,Ward 2,0207,25 Charles St,2129.0,42.382670,-71.070711,0101000020E6100000C320318986C451C0AD9BB750FB30...,Constituent Call
6,101003148273,2020-01-01 02:11:10,2020-01-03 03:30:00,2020-01-02 01:09:58,ONTIME,Closed,Case Closed. Closed date : 2020-01-02 06:09:58...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,South Boston / South Boston Waterfront,5,Ward 6,0607,723 E Second St,2127.0,42.337189,-71.034030,0101000020E6100000A4A0028E2DC251C000A27306292B...,Citizens Connect App
7,101003148274,2020-01-01 02:19:58,NaN,2020-01-01 03:19:48,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 08:19:48...,Needle Pickup,Mayor's 24 Hour Hotline,Needle Program,...,Jamaica Plain,11,Ward 11,1110,19 Spalding St,2130.0,42.303470,-71.113471,0101000020E610000085CC951A43C751C01B558317D826...,Citizens Connect App
8,101003148276,2020-01-01 02:56:41,2020-01-03 03:30:00,2020-01-02 00:08:04,ONTIME,Closed,Case Closed. Closed date : 2020-01-02 05:08:04...,CE Collection,Public Works Department,Street Cleaning,...,Charlestown,2,Ward 2,0203,12 Cedar St,2129.0,42.376590,-71.062240,0101000020E61000005F1A39BFFBC351C078D4E3153430...,City Worker App
9,101003148277,2020-01-01 03:08:52,2020-01-06 03:30:00,2020-01-01 03:48:39,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 08:48:39...,Improper Storage of Trash (Barrels),Public Works Department,Code Enforcement,...,Dorchester,8,Ward 16,1603,514 Talbot Ave,2124.0,42.287870,-71.065111,0101000020E610000028D7BAC52AC451C091B9AFE8D824...,Citizens Connect App
10,101003148278,2020-01-01 03:15:14,2020-01-03 03:30:00,2020-01-01 10:33:26,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 15:33:26...,Pick up Dead Animal,Public Works Department,Street Cleaning,...,South End,6,Ward 9,0902,194 W Springfield St,2118.0,42.340030,-71.080191,0101000020E610000082D47DD721C551C053299B16862B...,Citizens Connect App
11,101003148279,2020-01-01 03:17:00,2020-04-30 04:17:52,2020-01-06 02:14:58,ONTIME,Closed,Case Closed. Closed date : 2020-01-06 07:14:58...,Pest Infestation - Residential,Inspectional Services,Housing,...,Dorchester,7,16,1611,11 Granite Ave,2124.0,42.282256,-71.055839,0101000020E610000020533FDE92C351C09EC475F72024...,Citizens Connect App
12,101003148280,2020-01-01 03:20:30,2020-01-02 03:20:29,2020-01-01 07:40:14,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 12:40:14...,Traffic Signal Inspection,Transportation - Traffic Division,Signs & Signals,...,Dorchester,7,16,1606,INTERSECTION Ashmont St & Dorchester Ave,NaN,42.285752,-71.064309,0101000020E610000099D0E0A31DC451C0395CE8839324...,Citizens Connect App
13,101003148281,2020-01-01 03:24:00,2020-01-16 03:30:00,NaN,OVERDUE,Open,,Sign Repair,Transportation - Traffic Division,Signs & Signals,...,Dorchester,7,Ward 16,1611,2062 Dorchester Ave,2124.0,42.280450,-71.065521,0101000020E6100000BD3C787D31C451C0972839C5E523...,Citizens Connect App
14,101003148284,2020-01-01 03:31:00,2020-01-24 03:30:00,2020-01-09 04:50:10,ONTIME,Closed,Case Closed Case Resolved BROKEN CART#6144032...,Request for Recycling Cart,Public Works Department,Recycling,...,Charlestown,2,Ward 2,0207,67 Baldwin St,2129.0,42.382160,-71.070010,0101000020E61000004C07FC0C7BC451C0C851849AEA30...,City Worker App

In [8]:
print("Column Names and Data Types:")
print(data.dtypes)

Column Names and Data Types:
case_enquiry_id                     int64
open_dt                            object
sla_target_dt                      object
closed_dt                          object
on_time                            object
case_status                        object
closure_reason                     object
case_title                         object
subject                            object
reason                             object
type                               object
queue                              object
department                         object
submitted_photo                    object
closed_photo                       object
location                           object
fire_district                      object
pwd_district                       object
city_council_district              object
police_district                    object
neighborhood                       object
neighborhood_services_district     object
ward                               object
precinct                           object
location_street_name               object
location_zipcode                  float64
latitude                          float64
longitude                         float64
geom_4326                          object
source                             object
dtype: object

In [10]:
# Check if there are rows where `submitted_photo` or `closed_photo` are not NaN
non_nan_rows = data[(~data['submitted_photo'].isna()) | (~data['closed_photo'].isna())]

# Display the result
print(non_nan_rows)

# Count the number of non-NaN rows
print(f"Number of rows where either column is not NaN: {len(non_nan_rows)}")

         case_enquiry_id              open_dt        sla_target_dt  \
111         101003148392  2020-01-01 06:57:18  2020-03-09 04:30:00
116         101003148397  2020-01-01 07:06:34  2020-03-09 04:30:00
127         101003148409  2020-01-01 07:30:14  2020-03-09 04:30:00
131         101003148413  2020-01-01 07:37:59  2020-03-09 04:30:00
183         101003148471  2020-01-01 08:50:00  2020-01-16 03:30:00
...                  ...                  ...                  ...
2356200     101002279456  2017-12-05 21:08:31  2018-02-08 03:30:00
2356202     101002279459  2017-12-05 21:09:56  2018-02-08 03:30:00
2358566     101002282277  2017-12-09 20:11:00  2017-12-26 03:30:00
2358576     101002282294  2017-12-09 23:22:00  2017-12-26 03:30:00
2362691     101002287324  2017-12-16 21:07:35  2018-02-20 03:30:00

                   closed_dt  on_time case_status  \
111      2020-09-27 04:14:02  OVERDUE      Closed
116      2020-09-27 05:20:18  OVERDUE      Closed
127      2020-10-15 07:28:31  OVERDUE      Closed
131      2021-04-12 09:55:18  OVERDUE      Closed
183      2021-08-04 08:49:49  OVERDUE      Closed
...                      ...      ...         ...
2356200  2023-07-21 05:13:01  OVERDUE      Closed
2356202  2023-07-21 08:43:02  OVERDUE      Closed
2358566  2021-05-22 07:37:06  OVERDUE      Closed
2358576  2020-10-10 07:25:53  OVERDUE      Closed
2362691  2023-07-24 06:29:17  OVERDUE      Closed

                                            closure_reason  \
111      Case Closed. Closed date : Sun Sep 27 08:14:02...
116      Case Closed. Closed date : Sun Sep 27 09:20:18...
127      Case Closed. Closed date : Thu Oct 15 11:28:31...
131      Case Closed. Closed date : Mon Apr 12 13:55:18...
183      Case Closed. Closed date : Wed Aug 04 12:49:49...
...                                                    ...
2356200  Case Closed. Closed date : Fri Jul 21 09:13:01...
2356202  Case Closed. Closed date : Fri Jul 21 12:43:02...
2358566  Case Closed. Closed date : Sat May 22 11:37:06...
2358576  Case Closed. Closed date : Sat Oct 10 11:25:53...
2362691  Case Closed. Closed date : Mon Jul 24 10:29:17...

                              case_title                  subject  \
111                     Graffiti Removal      Property Management
116                     Graffiti Removal      Property Management
127                     Graffiti Removal      Property Management
131                     Graffiti Removal      Property Management
183      Printed - Gas Light Outage - EP  Public Works Department
...                                  ...                      ...
2356200                 Graffiti Removal      Property Management
2356202                 Graffiti Removal      Property Management
2358566                     PRINTED : JK  Public Works Department
2358576                     PRINTED : JK  Public Works Department
2362691                 Graffiti Removal      Property Management

                reason  ...                            neighborhood  \
111           Graffiti  ...                               Hyde Park
116           Graffiti  ...                               Hyde Park
127           Graffiti  ...                              Dorchester
131           Graffiti  ...                                 Roxbury
183      Street Lights  ...                             Beacon Hill
...                ...  ...                                     ...
2356200       Graffiti  ...                              Dorchester
2356202       Graffiti  ...                        Greater Mattapan
2358566  Street Lights  ...  South Boston / South Boston Waterfront
2358576  Street Lights  ...                             Beacon Hill
2362691       Graffiti  ...                               South End

        neighborhood_services_district     ward precinct  \
111                                 10  Ward 18     1820
116                                 10       18     1818
127                                  7  Ward 17     1704
131                                  8       14     1404
183                                 14   Ward 5     0503
...                                ...      ...      ...
2356200                              8       14     1407
2356202                              8  Ward 14     1407
2358566                              4        3     0308
2358576                             14        5     0503
2362691                              4        3     0307

                          location_street_name location_zipcode   latitude  \
111                            100 W Milton St           2136.0  42.238470
116         INTERSECTION Gordon Ave & River St              NaN  42.255621
127                          857 Washington St           2124.0  42.281740
131      INTERSECTION Morse St & Washington St              NaN  42.303939
183                        100 Mount Vernon St           2108.0  42.357790
...                                        ...              ...        ...
2356200                  730-742 Blue Hill Ave           2121.0  42.299787
2356202                      692 Blue Hill Ave           2121.0  42.300620
2358566  INTERSECTION Traveler St & W Broadway              NaN  42.344026
2358576    INTERSECTION Brimmer St & Beacon St              NaN  42.355732
2362691  INTERSECTION Perry St & Washington St              NaN  42.342817

         longitude                                          geom_4326  \
111     -71.135951  0101000020E610000075C24A6BB3C851C0A0BED02C861E...
116     -71.125575  0101000020E6100000C8ACCC6B09C851C03C597A31B820...
127     -71.071361  0101000020E6100000DA913F2C91C451C05D2A980A1024...
131     -71.078964  0101000020E61000004DACA3BF0DC551C02C79B977E726...
183     -71.069130  0101000020E6100000151E37A26CC451C0F37D260CCC2D...
...            ...                                                ...
2356200 -71.086052  0101000020E61000005F8D95E181C551C021F5996F5F26...
2356202 -71.085771  0101000020E610000024DB20447DC551C0CBE1A9B37A26...
2358566 -71.062064  0101000020E6100000B10108DDF8C351C0D1D2200C092C...
2358576 -71.071313  0101000020E610000096A44C6690C451C098C696A1882D...
2362691 -71.067052  0101000020E61000007303DF944AC451C067DF8E6DE12B...

                       source
111        Employee Generated
116        Employee Generated
127        Employee Generated
131        Employee Generated
183      Citizens Connect App
...                       ...
2356200  Citizens Connect App
2356202  Citizens Connect App
2358566  Citizens Connect App
2358576  Citizens Connect App
2362691  Citizens Connect App

[344719 rows x 30 columns]
Number of rows where either column is not NaN: 344719

In [17]:
combined_df = pd.concat(
    (pd.read_csv(file, dtype={'submitted_photo': str, 'closed_photo': str}) for file in all_files),
    ignore_index=True
)

In [18]:
combined_df['submitted_photo'] = combined_df['submitted_photo'].astype(str)
combined_df['closed_photo'] = combined_df['closed_photo'].astype(str)

In [19]:
# Save the DataFrame to a new CSV file
combined_df.to_csv("combined_cleaned_data.csv", index=False)

In [20]:
data1 = pd.read_csv('combined_cleaned_data.csv')
data1.head(15)

/var/folders/s9/tjqjhlhs57q4zp00qz4178gc0000gn/T/ipykernel_28918/1288416817.py:1: DtypeWarning: Columns (13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv('combined_cleaned_data.csv')

,case_enquiry_id,open_dt,sla_target_dt,closed_dt,on_time,case_status,closure_reason,case_title,subject,reason,...,neighborhood,neighborhood_services_district,ward,precinct,location_street_name,location_zipcode,latitude,longitude,geom_4326,source
0,101003148265,2020-01-01 00:07:00,2020-01-13 03:30:00,2020-01-20 06:43:10,OVERDUE,Closed,Case Closed. Closed date : 2020-01-20 11:43:10...,Park Lights - Doherty Playground (BPRD),Parks & Recreation Department,Park Maintenance & Safety,...,Charlestown,2,2,0207,INTERSECTION S Quincy Pl & Saint Martin St,NaN,42.382987,-71.067828,0101000020E6100000ADA5774957C451C01A77A6B30531...,Citizens Connect App
1,101003148266,2020-01-01 00:54:48,2020-01-01 00:54:48,2020-01-02 01:11:49,OVERDUE,Closed,Case Closed. Closed date : 2020-01-02 06:11:49...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,Dorchester,8,Ward 17,1702,85 Bloomfield St,2124.0,42.298900,-71.069541,0101000020E6100000E9E56F5A73C451C07E7212574226...,Citizens Connect App
2,101003148268,2020-01-01 01:14:13,2020-01-03 03:30:00,2020-01-01 10:05:46,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 15:05:46...,Requests for Street Cleaning,Public Works Department,Street Cleaning,...,South End,6,Ward 9,0901,423 Shawmut Ave,2118.0,42.340130,-71.074291,0101000020E6100000E2300A2DC1C451C0AAFE665D892B...,Citizens Connect App
3,101003148269,2020-01-01 01:19:00,2020-01-03 03:30:00,2020-01-02 01:10:56,ONTIME,Closed,Case Closed. Closed date : 2020-01-02 06:10:56...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,Roxbury,13,Ward 12,1201,6 Moreland St,2119.0,42.325960,-71.082761,0101000020E61000006A0602F34BC551C0EB78EE0AB929...,Constituent Call
4,101003148271,2020-01-01 02:02:00,2020-01-03 03:30:00,2020-01-01 02:07:17,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 07:07:17...,Missed Trash: District 1B,Public Works Department,Sanitation,...,Beacon Hill,14,Ward 5,0503,25-29 Charles St,2114.0,42.356920,-71.069650,0101000020E61000001AD6442775C451C0A731108AAF2D...,Constituent Call
5,101003148272,2020-01-01 02:04:00,2020-01-03 03:30:00,2020-01-01 03:11:52,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 08:11:52...,Missed Trash: District 1A,Public Works Department,Sanitation,...,Charlestown,2,Ward 2,0207,25 Charles St,2129.0,42.382670,-71.070711,0101000020E6100000C320318986C451C0AD9BB750FB30...,Constituent Call
6,101003148273,2020-01-01 02:11:10,2020-01-03 03:30:00,2020-01-02 01:09:58,ONTIME,Closed,Case Closed. Closed date : 2020-01-02 06:09:58...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,South Boston / South Boston Waterfront,5,Ward 6,0607,723 E Second St,2127.0,42.337189,-71.034030,0101000020E6100000A4A0028E2DC251C000A27306292B...,Citizens Connect App
7,101003148274,2020-01-01 02:19:58,NaN,2020-01-01 03:19:48,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 08:19:48...,Needle Pickup,Mayor's 24 Hour Hotline,Needle Program,...,Jamaica Plain,11,Ward 11,1110,19 Spalding St,2130.0,42.303470,-71.113471,0101000020E610000085CC951A43C751C01B558317D826...,Citizens Connect App
8,101003148276,2020-01-01 02:56:41,2020-01-03 03:30:00,2020-01-02 00:08:04,ONTIME,Closed,Case Closed. Closed date : 2020-01-02 05:08:04...,CE Collection,Public Works Department,Street Cleaning,...,Charlestown,2,Ward 2,0203,12 Cedar St,2129.0,42.376590,-71.062240,0101000020E61000005F1A39BFFBC351C078D4E3153430...,City Worker App
9,101003148277,2020-01-01 03:08:52,2020-01-06 03:30:00,2020-01-01 03:48:39,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 08:48:39...,Improper Storage of Trash (Barrels),Public Works Department,Code Enforcement,...,Dorchester,8,Ward 16,1603,514 Talbot Ave,2124.0,42.287870,-71.065111,0101000020E610000028D7BAC52AC451C091B9AFE8D824...,Citizens Connect App
10,101003148278,2020-01-01 03:15:14,2020-01-03 03:30:00,2020-01-01 10:33:26,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 15:33:26...,Pick up Dead Animal,Public Works Department,Street Cleaning,...,South End,6,Ward 9,0902,194 W Springfield St,2118.0,42.340030,-71.080191,0101000020E610000082D47DD721C551C053299B16862B...,Citizens Connect App
11,101003148279,2020-01-01 03:17:00,2020-04-30 04:17:52,2020-01-06 02:14:58,ONTIME,Closed,Case Closed. Closed date : 2020-01-06 07:14:58...,Pest Infestation - Residential,Inspectional Services,Housing,...,Dorchester,7,16,1611,11 Granite Ave,2124.0,42.282256,-71.055839,0101000020E610000020533FDE92C351C09EC475F72024...,Citizens Connect App
12,101003148280,2020-01-01 03:20:30,2020-01-02 03:20:29,2020-01-01 07:40:14,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 12:40:14...,Traffic Signal Inspection,Transportation - Traffic Division,Signs & Signals,...,Dorchester,7,16,1606,INTERSECTION Ashmont St & Dorchester Ave,NaN,42.285752,-71.064309,0101000020E610000099D0E0A31DC451C0395CE8839324...,Citizens Connect App
13,101003148281,2020-01-01 03:24:00,2020-01-16 03:30:00,NaN,OVERDUE,Open,,Sign Repair,Transportation - Traffic Division,Signs & Signals,...,Dorchester,7,Ward 16,1611,2062 Dorchester Ave,2124.0,42.280450,-71.065521,0101000020E6100000BD3C787D31C451C0972839C5E523...,Citizens Connect App
14,101003148284,2020-01-01 03:31:00,2020-01-24 03:30:00,2020-01-09 04:50:10,ONTIME,Closed,Case Closed Case Resolved BROKEN CART#6144032...,Request for Recycling Cart,Public Works Department,Recycling,...,Charlestown,2,Ward 2,0207,67 Baldwin St,2129.0,42.382160,-71.070010,0101000020E61000004C07FC0C7BC451C0C851849AEA30...,City Worker App

In [22]:
data = pd.read_csv('combined_file.csv')
data.head(15)

/var/folders/s9/tjqjhlhs57q4zp00qz4178gc0000gn/T/ipykernel_28918/3649526037.py:1: DtypeWarning: Columns (13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('combined_file.csv')

,case_enquiry_id,open_dt,sla_target_dt,closed_dt,on_time,case_status,closure_reason,case_title,subject,reason,...,neighborhood,neighborhood_services_district,ward,precinct,location_street_name,location_zipcode,latitude,longitude,geom_4326,source
0,101003148265,2020-01-01 00:07:00,2020-01-13 03:30:00,2020-01-20 06:43:10,OVERDUE,Closed,Case Closed. Closed date : 2020-01-20 11:43:10...,Park Lights - Doherty Playground (BPRD),Parks & Recreation Department,Park Maintenance & Safety,...,Charlestown,2,2,0207,INTERSECTION S Quincy Pl & Saint Martin St,NaN,42.382987,-71.067828,0101000020E6100000ADA5774957C451C01A77A6B30531...,Citizens Connect App
1,101003148266,2020-01-01 00:54:48,2020-01-01 00:54:48,2020-01-02 01:11:49,OVERDUE,Closed,Case Closed. Closed date : 2020-01-02 06:11:49...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,Dorchester,8,Ward 17,1702,85 Bloomfield St,2124.0,42.298900,-71.069541,0101000020E6100000E9E56F5A73C451C07E7212574226...,Citizens Connect App
2,101003148268,2020-01-01 01:14:13,2020-01-03 03:30:00,2020-01-01 10:05:46,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 15:05:46...,Requests for Street Cleaning,Public Works Department,Street Cleaning,...,South End,6,Ward 9,0901,423 Shawmut Ave,2118.0,42.340130,-71.074291,0101000020E6100000E2300A2DC1C451C0AAFE665D892B...,Citizens Connect App
3,101003148269,2020-01-01 01:19:00,2020-01-03 03:30:00,2020-01-02 01:10:56,ONTIME,Closed,Case Closed. Closed date : 2020-01-02 06:10:56...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,Roxbury,13,Ward 12,1201,6 Moreland St,2119.0,42.325960,-71.082761,0101000020E61000006A0602F34BC551C0EB78EE0AB929...,Constituent Call
4,101003148271,2020-01-01 02:02:00,2020-01-03 03:30:00,2020-01-01 02:07:17,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 07:07:17...,Missed Trash: District 1B,Public Works Department,Sanitation,...,Beacon Hill,14,Ward 5,0503,25-29 Charles St,2114.0,42.356920,-71.069650,0101000020E61000001AD6442775C451C0A731108AAF2D...,Constituent Call
5,101003148272,2020-01-01 02:04:00,2020-01-03 03:30:00,2020-01-01 03:11:52,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 08:11:52...,Missed Trash: District 1A,Public Works Department,Sanitation,...,Charlestown,2,Ward 2,0207,25 Charles St,2129.0,42.382670,-71.070711,0101000020E6100000C320318986C451C0AD9BB750FB30...,Constituent Call
6,101003148273,2020-01-01 02:11:10,2020-01-03 03:30:00,2020-01-02 01:09:58,ONTIME,Closed,Case Closed. Closed date : 2020-01-02 06:09:58...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,South Boston / South Boston Waterfront,5,Ward 6,0607,723 E Second St,2127.0,42.337189,-71.034030,0101000020E6100000A4A0028E2DC251C000A27306292B...,Citizens Connect App
7,101003148274,2020-01-01 02:19:58,NaN,2020-01-01 03:19:48,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 08:19:48...,Needle Pickup,Mayor's 24 Hour Hotline,Needle Program,...,Jamaica Plain,11,Ward 11,1110,19 Spalding St,2130.0,42.303470,-71.113471,0101000020E610000085CC951A43C751C01B558317D826...,Citizens Connect App
8,101003148276,2020-01-01 02:56:41,2020-01-03 03:30:00,2020-01-02 00:08:04,ONTIME,Closed,Case Closed. Closed date : 2020-01-02 05:08:04...,CE Collection,Public Works Department,Street Cleaning,...,Charlestown,2,Ward 2,0203,12 Cedar St,2129.0,42.376590,-71.062240,0101000020E61000005F1A39BFFBC351C078D4E3153430...,City Worker App
9,101003148277,2020-01-01 03:08:52,2020-01-06 03:30:00,2020-01-01 03:48:39,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 08:48:39...,Improper Storage of Trash (Barrels),Public Works Department,Code Enforcement,...,Dorchester,8,Ward 16,1603,514 Talbot Ave,2124.0,42.287870,-71.065111,0101000020E610000028D7BAC52AC451C091B9AFE8D824...,Citizens Connect App
10,101003148278,2020-01-01 03:15:14,2020-01-03 03:30:00,2020-01-01 10:33:26,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 15:33:26...,Pick up Dead Animal,Public Works Department,Street Cleaning,...,South End,6,Ward 9,0902,194 W Springfield St,2118.0,42.340030,-71.080191,0101000020E610000082D47DD721C551C053299B16862B...,Citizens Connect App
11,101003148279,2020-01-01 03:17:00,2020-04-30 04:17:52,2020-01-06 02:14:58,ONTIME,Closed,Case Closed. Closed date : 2020-01-06 07:14:58...,Pest Infestation - Residential,Inspectional Services,Housing,...,Dorchester,7,16,1611,11 Granite Ave,2124.0,42.282256,-71.055839,0101000020E610000020533FDE92C351C09EC475F72024...,Citizens Connect App
12,101003148280,2020-01-01 03:20:30,2020-01-02 03:20:29,2020-01-01 07:40:14,ONTIME,Closed,Case Closed. Closed date : 2020-01-01 12:40:14...,Traffic Signal Inspection,Transportation - Traffic Division,Signs & Signals,...,Dorchester,7,16,1606,INTERSECTION Ashmont St & Dorchester Ave,NaN,42.285752,-71.064309,0101000020E610000099D0E0A31DC451C0395CE8839324...,Citizens Connect App
13,101003148281,2020-01-01 03:24:00,2020-01-16 03:30:00,NaN,OVERDUE,Open,,Sign Repair,Transportation - Traffic Division,Signs & Signals,...,Dorchester,7,Ward 16,1611,2062 Dorchester Ave,2124.0,42.280450,-71.065521,0101000020E6100000BD3C787D31C451C0972839C5E523...,Citizens Connect App
14,101003148284,2020-01-01 03:31:00,2020-01-24 03:30:00,2020-01-09 04:50:10,ONTIME,Closed,Case Closed Case Resolved BROKEN CART#6144032...,Request for Recycling Cart,Public Works Department,Recycling,...,Charlestown,2,Ward 2,0207,67 Baldwin St,2129.0,42.382160,-71.070010,0101000020E61000004C07FC0C7BC451C0C851849AEA30...,City Worker App

In [23]:
# Ensure the "open_dt" column is treated as a string (in case it isn't already)
data['open_dt'] = data['open_dt'].astype(str)

# Extract the first four characters from the "open_dt" column and create a new column "Year"
data['Year'] = data['open_dt'].str[:4]

# Check the updated DataFrame
print(data[['open_dt', 'Year']].head())

               open_dt  Year
0  2020-01-01 00:07:00  2020
1  2020-01-01 00:54:48  2020
2  2020-01-01 01:14:13  2020
3  2020-01-01 01:19:00  2020
4  2020-01-01 02:02:00  2020

In [24]:
data.to_csv("combined_with_year.csv", index=False)