In [160]:
import pandas as pd
import numpy as np
import geopandas as gpd
from geopy.geocoders import Nominatim
import re

In [164]:
df = pd.read_excel("..\\..\\FinalData\\geocoded_student_addresses.xlsx")

In [165]:
df.head()

,6a. street #,6b. street name,6c. street suffix,6d. unit #,6e. zip,7. undergraduate (u) or graduate (g),8. full-time (ft) or part-time (pt),9. at-home or not-at-home,9. 5 or more undergrads/unit (y/n),university,year,Latitude,Longitude
0,10,Higgins,ST,NaN,02134,U,FT,NaN,NaN,Emmanuel College,2018-2019,42.356451,-71.131212
1,10,Higgins,ST,NaN,02134,U,FT,NaN,NaN,Emmanuel College,2018-2019,42.356451,-71.131212
2,1189,Commonwealth,AVE,6,02134,U,FT,NaN,NaN,Emmanuel College,2018-2019,42.356451,-71.131212
3,12,Glenville,AVE,NaN,02134,U,FT,NaN,NaN,Emmanuel College,2018-2019,42.356451,-71.131212
4,12,Glenville,AVE,1,02134,U,FT,NaN,NaN,Emmanuel College,2018-2019,42.356451,-71.131212

In [7]:
df.columns

Index(['6a. street #', '6b. street name', '6c. street suffix', '6d. unit #',
       '6e. zip', '7. undergraduate (u) or graduate (g)',
       '8. full-time (ft) or part-time (pt)', '9. at-home or not-at-home',
       '9. 5 or more undergrads/unit (y/n)', 'university', 'year', 'Latitude',
       'Longitude'],
      dtype='object')

In [12]:
pattern = r'^0\d{4}$'
df = df[df['6e. zip'].astype(str).apply(lambda x: bool(re.match(pattern, x)))]

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 294090 entries, 0 to 310330
Data columns (total 13 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   6a. street #                          287942 non-null  object
 1   6b. street name                       287542 non-null  object
 2   6c. street suffix                     262907 non-null  object
 3   6d. unit #                            190923 non-null  object
 4   6e. zip                               294090 non-null  object
 5   7. undergraduate (u) or graduate (g)  294086 non-null  object
 6   8. full-time (ft) or part-time (pt)   293980 non-null  object
 7   9. at-home or not-at-home             203402 non-null  object
 8   9. 5 or more undergrads/unit (y/n)    62314 non-null   object
 9   university                            294090 non-null  object
 10  year                                  294090 non-null  object
 11  Latitude                              286948 non-null  float64
 12  Longitude                             286948 non-null  float64
dtypes: float64(2), object(11)
memory usage: 31.4+ MB

In [18]:
szip = set(df["6e. zip"].unique())

In [19]:
nzip = set(shapefile.ZIP5)

In [66]:
nzip

{'02021',
 '02026',
 '02108',
 '02109',
 '02110',
 '02111',
 '02113',
 '02114',
 '02115',
 '02116',
 '02118',
 '02119',
 '02120',
 '02121',
 '02122',
 '02124',
 '02125',
 '02126',
 '02127',
 '02128',
 '02129',
 '02130',
 '02131',
 '02132',
 '02134',
 '02135',
 '02136',
 '02151',
 '02152',
 '02163',
 '02186',
 '02199',
 '02203',
 '02210',
 '02215',
 '02459',
 '02467'}

In [20]:
print(len(nzip),len(szip))

37 117

In [68]:
nzip = nzip.intersection(szip)

In [23]:
len(diff_zips)

84

In [69]:
temp = df[df["6e. zip"].isin(list(nzip))]

In [72]:
temp2 = temp.groupby(["6e. zip","year"]).count().sort_values("university",ascending=False).reset_index()

In [108]:
temp3 = temp2.iloc[:,:3]

In [109]:
temp3.columns = ["ZIP5","year","count"]

In [110]:
temp3["ZIP5"].unique()

array(['02134', '02115', '02215', '02120', '02135', '02130', '02118',
       '02125', '02119', '02128', '02116', '02114', '02111', '02124',
       '02127', '02113', '02121', '02122', '02136', '02131', '02132',
       '02129', '02126', '02108', '02109', '02210', '02110', '02199',
       '02152', '02467', '02151', '02163', '02021'], dtype=object)

In [33]:
years = zips["year"].unique()

In [91]:
temp3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ZIP5    257 non-null    object
 1   year    257 non-null    object
 2   count   257 non-null    int64
dtypes: int64(1), object(2)
memory usage: 6.2+ KB

In [92]:
temp3["ZIP5"] = temp3["ZIP5"].astype(str)

In [93]:
temp3

      ZIP5       year  count
0    02134  2017-2018   7139
1    02115  2023-2024   6052
2    02115  2022-2023   5857
3    02215  2017-2018   5539
4    02120  2023-2024   5212
..     ...        ...    ...
252  02021  2021-2022      2
253  02467  2016-2017      2
254  02163  2023-2024      2
255  02021  2020-2021      1
256  02021  2022-2023      1

[257 rows x 3 columns]

In [111]:
temp4 = pd.read_csv("Updated_Zip_Code_and_Neighborhood_Mapping.csv",dtype='str')

In [112]:
temp4.columns = ['ZIP5','Neighbourhood']

In [113]:
temp4["ZIP5"].unique()

array(['02134', '02135', '02163', '02116', '02117', '02123', '02133',
       '02199', '02108', '02129', '02111', '02122', '02124', '02125',
       '02109', '02110', '02113', '02114', '02128', '02228', '02115', nan,
       '02136', '02130', '02126', '02120', '02131', '02119', '02121',
       '02127', '02210', '02118', '02132', '02215', '02152', '02467',
       '02151', '02021'], dtype=object)

In [114]:
temp3 = temp3.merge(temp4, on="ZIP5")

In [115]:
temp3

      ZIP5       year  count  Neighbourhood
0    02134  2017-2018   7139        Allston
1    02115  2023-2024   6052         Fenway
2    02115  2023-2024   6052       Longwood
3    02115  2022-2023   5857         Fenway
4    02115  2022-2023   5857       Longwood
..     ...        ...    ...            ...
292  02021  2021-2022      2         Canton
293  02467  2016-2017      2  Chestnut Hill
294  02163  2023-2024      2       Brighton
295  02021  2020-2021      1         Canton
296  02021  2022-2023      1         Canton

[297 rows x 4 columns]

In [116]:
temp3["ZIP5"].unique()

array(['02134', '02115', '02215', '02120', '02135', '02130', '02118',
       '02125', '02119', '02128', '02116', '02114', '02111', '02124',
       '02127', '02113', '02121', '02122', '02136', '02131', '02132',
       '02129', '02126', '02108', '02109', '02210', '02110', '02199',
       '02152', '02467', '02151', '02163', '02021'], dtype=object)

In [118]:
temp3.to_csv("Population_byZip_byYear.csv",index=False)